<?php

namespace Database\Seeders;

use App\Models\ApiEndpoint;
use Illuminate\Database\Seeder;

class ApiEndpointSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $endpoints = [
            // ============================================
            // Authentication
            // ============================================
            [
                'name' => 'เข้าสู่ระบบ',
                'path' => 'api/v1/login',
                'method' => 'POST',
                'category' => 'Authentication',
                'description' => 'เข้าสู่ระบบด้วย email และ password รับ token สำหรับการยืนยันตัวตน',
                'is_active' => true,
                'requires_auth' => false,
                'rate_limit_per_minute' => 5,
                'rate_limit_per_hour' => 20,
                'rate_limit_per_day' => 100,
                'allowed_roles' => null,
                'priority' => 1,
            ],
            [
                'name' => 'ออกจากระบบ',
                'path' => 'api/v1/logout',
                'method' => 'POST',
                'category' => 'Authentication',
                'description' => 'ออกจากระบบและยกเลิก access token',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 10,
                'rate_limit_per_hour' => 100,
                'rate_limit_per_day' => 500,
                'allowed_roles' => ['admin', 'user', 'seller'],
                'priority' => 2,
            ],
            [
                'name' => 'ข้อมูลผู้ใช้ปัจจุบัน',
                'path' => 'api/v1/me',
                'method' => 'GET',
                'category' => 'Authentication',
                'description' => 'ดึงข้อมูลผู้ใช้ที่ login อยู่',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user', 'seller'],
                'priority' => 3,
            ],

            // ============================================
            // Dashboard
            // ============================================
            [
                'name' => 'สถิติ Dashboard',
                'path' => 'api/v1/dashboard/statistics',
                'method' => 'GET',
                'category' => 'Dashboard',
                'description' => 'ดึงข้อมูลสถิติภาพรวมสำหรับ Dashboard',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user', 'seller'],
                'priority' => 10,
            ],
            [
                'name' => 'คอมมิชชั่น Dashboard',
                'path' => 'api/v1/dashboard/commissions',
                'method' => 'GET',
                'category' => 'Dashboard',
                'description' => 'ดึงข้อมูลคอมมิชชั่นของผู้ใช้',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user', 'seller'],
                'priority' => 11,
            ],
            [
                'name' => 'รายชื่อผู้แนะนำ',
                'path' => 'api/v1/dashboard/referrals',
                'method' => 'GET',
                'category' => 'Dashboard',
                'description' => 'ดึงรายชื่อผู้ที่ถูกแนะนำ',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user', 'seller'],
                'priority' => 12,
            ],
            [
                'name' => 'การตั้งค่า App',
                'path' => 'api/v1/settings',
                'method' => 'GET',
                'category' => 'Dashboard',
                'description' => 'ดึงการตั้งค่าแอปพลิเคชัน (public)',
                'is_active' => true,
                'requires_auth' => false,
                'rate_limit_per_minute' => 100,
                'rate_limit_per_hour' => 2000,
                'rate_limit_per_day' => 20000,
                'allowed_roles' => null,
                'priority' => 13,
            ],

            // ============================================
            // Tree (Organization Chart)
            // ============================================
            [
                'name' => 'โครงสร้างองค์กรผู้ใช้',
                'path' => 'api/v1/tree/user',
                'method' => 'GET',
                'category' => 'Tree',
                'description' => 'ดึงโครงสร้างองค์กรของผู้ใช้',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 20,
            ],
            [
                'name' => 'โครงสร้างองค์กร Admin',
                'path' => 'api/v1/tree/admin/{affiliateId?}',
                'method' => 'GET',
                'category' => 'Tree',
                'description' => 'ดึงโครงสร้างองค์กรสำหรับ Admin',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin'],
                'priority' => 21,
            ],
            [
                'name' => 'โครงสร้างแบบ Binary',
                'path' => 'api/v1/tree/binary',
                'method' => 'GET',
                'category' => 'Tree',
                'description' => 'ดึงโครงสร้างแบบ Binary ของผู้ใช้',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 22,
            ],
            [
                'name' => 'โครงสร้าง Binary Admin',
                'path' => 'api/v1/tree/binary/admin/{affiliateId?}',
                'method' => 'GET',
                'category' => 'Tree',
                'description' => 'ดึงโครงสร้าง Binary สำหรับ Admin',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin'],
                'priority' => 23,
            ],

            // ============================================
            // Ranks
            // ============================================
            [
                'name' => 'รายการยศทั้งหมด',
                'path' => 'api/v1/ranks',
                'method' => 'GET',
                'category' => 'Ranks',
                'description' => 'ดึงรายการยศทั้งหมด',
                'is_active' => true,
                'requires_auth' => false,
                'rate_limit_per_minute' => 100,
                'rate_limit_per_hour' => 2000,
                'rate_limit_per_day' => 20000,
                'allowed_roles' => null,
                'priority' => 30,
            ],
            [
                'name' => 'รายละเอียดยศ',
                'path' => 'api/v1/ranks/{rank}',
                'method' => 'GET',
                'category' => 'Ranks',
                'description' => 'ดึงรายละเอียดยศตาม ID',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 31,
            ],
            [
                'name' => 'ความคืบหน้ายศผู้ใช้',
                'path' => 'api/v1/ranks/user/progress',
                'method' => 'GET',
                'category' => 'Ranks',
                'description' => 'ดึงความคืบหน้ายศของผู้ใช้',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 32,
            ],
            [
                'name' => 'กระดานผู้นำยศ',
                'path' => 'api/v1/ranks/leaderboard',
                'method' => 'GET',
                'category' => 'Ranks',
                'description' => 'ดึงกระดานผู้นำยศ',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 33,
            ],
            [
                'name' => 'ตรวจสอบคุณสมบัติยศ',
                'path' => 'api/v1/ranks/user/eligibility',
                'method' => 'GET',
                'category' => 'Ranks',
                'description' => 'ตรวจสอบคุณสมบัติในการขึ้นยศ',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 34,
            ],
            [
                'name' => 'ขอขึ้นยศ',
                'path' => 'api/v1/ranks/promotions/request',
                'method' => 'POST',
                'category' => 'Ranks',
                'description' => 'ส่งคำขอขึ้นยศ',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 10,
                'rate_limit_per_hour' => 50,
                'rate_limit_per_day' => 200,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 35,
            ],

            // ============================================
            // Investments & Staking
            // ============================================
            [
                'name' => 'แผนการลงทุน',
                'path' => 'api/v1/investments/plans',
                'method' => 'GET',
                'category' => 'Investments',
                'description' => 'ดึงรายการแผนการลงทุนทั้งหมด',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 40,
            ],
            [
                'name' => 'รายละเอียดแผนการลงทุน',
                'path' => 'api/v1/investments/plans/{plan}',
                'method' => 'GET',
                'category' => 'Investments',
                'description' => 'ดึงรายละเอียดแผนการลงทุน',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 41,
            ],
            [
                'name' => 'คำนวณ ROI',
                'path' => 'api/v1/investments/calculate-roi',
                'method' => 'POST',
                'category' => 'Investments',
                'description' => 'คำนวณผลตอบแทนจากการลงทุน',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 30,
                'rate_limit_per_hour' => 500,
                'rate_limit_per_day' => 5000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 42,
            ],
            [
                'name' => 'ลงทุน',
                'path' => 'api/v1/investments/invest',
                'method' => 'POST',
                'category' => 'Investments',
                'description' => 'สร้างการลงทุนใหม่',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 10,
                'rate_limit_per_hour' => 100,
                'rate_limit_per_day' => 500,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 43,
            ],
            [
                'name' => 'สรุปการลงทุน',
                'path' => 'api/v1/investments/summary',
                'method' => 'GET',
                'category' => 'Investments',
                'description' => 'สรุปภาพรวมการลงทุนของผู้ใช้',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 44,
            ],
            [
                'name' => 'รายการ Positions',
                'path' => 'api/v1/investments/positions',
                'method' => 'GET',
                'category' => 'Investments',
                'description' => 'ดึงรายการ positions การลงทุน',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 45,
            ],
            [
                'name' => 'รายละเอียด Position',
                'path' => 'api/v1/investments/positions/{position}',
                'method' => 'GET',
                'category' => 'Investments',
                'description' => 'ดึงรายละเอียด position การลงทุน',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 46,
            ],
            [
                'name' => 'ถอนเงินลงทุน',
                'path' => 'api/v1/investments/positions/{position}/withdraw',
                'method' => 'POST',
                'category' => 'Investments',
                'description' => 'ถอนเงินจาก position การลงทุน',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 10,
                'rate_limit_per_hour' => 100,
                'rate_limit_per_day' => 500,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 47,
            ],
            [
                'name' => 'ประวัติการจ่ายผลตอบแทน',
                'path' => 'api/v1/investments/distributions',
                'method' => 'GET',
                'category' => 'Investments',
                'description' => 'ดึงประวัติการจ่ายผลตอบแทน',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 48,
            ],

            // ============================================
            // Crypto Wallet
            // ============================================
            [
                'name' => 'สร้าง Nonce',
                'path' => 'api/crypto/generate-nonce',
                'method' => 'POST',
                'category' => 'Crypto Wallet',
                'description' => 'สร้าง nonce สำหรับการยืนยันตัวตน (public)',
                'is_active' => true,
                'requires_auth' => false,
                'rate_limit_per_minute' => 10,
                'rate_limit_per_hour' => 100,
                'rate_limit_per_day' => 500,
                'allowed_roles' => null,
                'priority' => 50,
            ],
            [
                'name' => 'ตรวจสอบลายเซ็น',
                'path' => 'api/v1/crypto/verify-signature',
                'method' => 'POST',
                'category' => 'Crypto Wallet',
                'description' => 'ตรวจสอบลายเซ็นดิจิทัล',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 20,
                'rate_limit_per_hour' => 200,
                'rate_limit_per_day' => 1000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 51,
            ],
            [
                'name' => 'ยอดเงิน Crypto',
                'path' => 'api/v1/crypto/balances',
                'method' => 'GET',
                'category' => 'Crypto Wallet',
                'description' => 'ดึงยอดเงินคริปโตทั้งหมด',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 52,
            ],
            [
                'name' => 'ที่อยู่ Crypto',
                'path' => 'api/v1/crypto/address/{currency}',
                'method' => 'GET',
                'category' => 'Crypto Wallet',
                'description' => 'ดึงที่อยู่กระเป๋าเงินตามสกุลเงิน',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 53,
            ],
            [
                'name' => 'ราคา Crypto',
                'path' => 'api/v1/crypto/prices',
                'method' => 'GET',
                'category' => 'Crypto Wallet',
                'description' => 'ดึงราคาคริปโตปัจจุบัน',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 100,
                'rate_limit_per_hour' => 2000,
                'rate_limit_per_day' => 20000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 54,
            ],
            [
                'name' => 'ตรวจสอบธุรกรรม',
                'path' => 'api/v1/crypto/transaction/{txHash}',
                'method' => 'GET',
                'category' => 'Crypto Wallet',
                'description' => 'ตรวจสอบสถานะธุรกรรม',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 55,
            ],
            [
                'name' => 'ราคา Gas',
                'path' => 'api/v1/crypto/gas-price',
                'method' => 'GET',
                'category' => 'Crypto Wallet',
                'description' => 'ดึงราคา gas ปัจจุบัน',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 100,
                'rate_limit_per_hour' => 2000,
                'rate_limit_per_day' => 20000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 56,
            ],

            // ============================================
            // NFC Card
            // ============================================
            [
                'name' => 'รายการบัตร NFC',
                'path' => 'api/v1/nfc/cards',
                'method' => 'GET',
                'category' => 'NFC Card',
                'description' => 'ดึงรายการบัตร NFC ทั้งหมด',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 60,
            ],
            [
                'name' => 'รายละเอียดบัตร NFC',
                'path' => 'api/v1/nfc/cards/{cardId}',
                'method' => 'GET',
                'category' => 'NFC Card',
                'description' => 'ดึงรายละเอียดบัตร NFC',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 61,
            ],
            [
                'name' => 'ตรวจสอบบัตร NFC',
                'path' => 'api/v1/nfc/cards/verify',
                'method' => 'POST',
                'category' => 'NFC Card',
                'description' => 'ตรวจสอบความถูกต้องบัตร NFC',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 30,
                'rate_limit_per_hour' => 300,
                'rate_limit_per_day' => 2000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 62,
            ],
            [
                'name' => 'ชำระเงินด้วยบัตร NFC',
                'path' => 'api/v1/nfc/cards/payment',
                'method' => 'POST',
                'category' => 'NFC Card',
                'description' => 'ทำการชำระเงินด้วยบัตร NFC',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 10,
                'rate_limit_per_hour' => 100,
                'rate_limit_per_day' => 500,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 63,
            ],
            [
                'name' => 'ธุรกรรมบัตร NFC',
                'path' => 'api/v1/nfc/cards/{cardId}/transactions',
                'method' => 'GET',
                'category' => 'NFC Card',
                'description' => 'ดึงประวัติธุรกรรมบัตร NFC',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 64,
            ],
            [
                'name' => 'ยอดเงินบัตร NFC',
                'path' => 'api/v1/nfc/cards/{cardId}/balance',
                'method' => 'GET',
                'category' => 'NFC Card',
                'description' => 'ดึงยอดเงินบัตร NFC',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 65,
            ],
            [
                'name' => 'เครื่องอ่านบัตรใกล้เคียง',
                'path' => 'api/v1/nfc/readers/nearby',
                'method' => 'GET',
                'category' => 'NFC Card',
                'description' => 'ค้นหาเครื่องอ่านบัตรใกล้เคียง',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 30,
                'rate_limit_per_hour' => 500,
                'rate_limit_per_day' => 5000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 66,
            ],

            // ============================================
            // TPIX Blockchain
            // ============================================
            [
                'name' => 'ข้อมูลเครือข่าย TPIX',
                'path' => 'api/v1/tpix/network-info',
                'method' => 'GET',
                'category' => 'TPIX Blockchain',
                'description' => 'ดึงข้อมูลเครือข่าย TPIX',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 70,
            ],
            [
                'name' => 'ยอดเงิน TPIX',
                'path' => 'api/v1/tpix/balance',
                'method' => 'GET',
                'category' => 'TPIX Blockchain',
                'description' => 'ดึงยอดเงิน TPIX',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 71,
            ],
            [
                'name' => 'เลขบล็อกปัจจุบัน',
                'path' => 'api/v1/tpix/block-number',
                'method' => 'GET',
                'category' => 'TPIX Blockchain',
                'description' => 'ดึงเลขบล็อกปัจจุบัน',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 100,
                'rate_limit_per_hour' => 2000,
                'rate_limit_per_day' => 20000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 72,
            ],
            [
                'name' => 'ข้อมูลธุรกรรม TPIX',
                'path' => 'api/v1/tpix/transaction',
                'method' => 'GET',
                'category' => 'TPIX Blockchain',
                'description' => 'ดึงข้อมูลธุรกรรม TPIX',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 73,
            ],
            [
                'name' => 'ใบเสร็จธุรกรรม TPIX',
                'path' => 'api/v1/tpix/transaction-receipt',
                'method' => 'GET',
                'category' => 'TPIX Blockchain',
                'description' => 'ดึงใบเสร็จธุรกรรม TPIX',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 74,
            ],
            [
                'name' => 'ส่งธุรกรรม Raw TPIX',
                'path' => 'api/v1/tpix/send-raw-transaction',
                'method' => 'POST',
                'category' => 'TPIX Blockchain',
                'description' => 'ส่งธุรกรรม raw ไปยัง blockchain',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 20,
                'rate_limit_per_hour' => 200,
                'rate_limit_per_day' => 1000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 75,
            ],
            [
                'name' => 'ประมาณค่า Gas TPIX',
                'path' => 'api/v1/tpix/estimate-gas',
                'method' => 'POST',
                'category' => 'TPIX Blockchain',
                'description' => 'ประมาณค่า gas สำหรับธุรกรรม',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 76,
            ],
            [
                'name' => 'ราคา Gas TPIX',
                'path' => 'api/v1/tpix/gas-price',
                'method' => 'GET',
                'category' => 'TPIX Blockchain',
                'description' => 'ดึงราคา gas ปัจจุบัน',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 100,
                'rate_limit_per_hour' => 2000,
                'rate_limit_per_day' => 20000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 77,
            ],
            [
                'name' => 'จำนวนธุรกรรม TPIX',
                'path' => 'api/v1/tpix/transaction-count',
                'method' => 'GET',
                'category' => 'TPIX Blockchain',
                'description' => 'ดึงจำนวนธุรกรรมของที่อยู่',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 78,
            ],
            [
                'name' => 'ตรวจสอบที่อยู่ TPIX',
                'path' => 'api/v1/tpix/validate-address',
                'method' => 'POST',
                'category' => 'TPIX Blockchain',
                'description' => 'ตรวจสอบความถูกต้องที่อยู่',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 79,
            ],
            [
                'name' => 'แปลงเป็น Wei',
                'path' => 'api/v1/tpix/to-wei',
                'method' => 'POST',
                'category' => 'TPIX Blockchain',
                'description' => 'แปลง TPIX เป็น Wei',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 100,
                'rate_limit_per_hour' => 2000,
                'rate_limit_per_day' => 20000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 80,
            ],
            [
                'name' => 'แปลงจาก Wei',
                'path' => 'api/v1/tpix/from-wei',
                'method' => 'POST',
                'category' => 'TPIX Blockchain',
                'description' => 'แปลง Wei เป็น TPIX',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 100,
                'rate_limit_per_hour' => 2000,
                'rate_limit_per_day' => 20000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 81,
            ],

            // ============================================
            // App Configuration
            // ============================================
            [
                'name' => 'สถานะการบำรุงรักษา',
                'path' => 'api/v1/app/maintenance-status',
                'method' => 'GET',
                'category' => 'App Configuration',
                'description' => 'ตรวจสอบสถานะการบำรุงรักษา (public)',
                'is_active' => true,
                'requires_auth' => false,
                'rate_limit_per_minute' => 100,
                'rate_limit_per_hour' => 2000,
                'rate_limit_per_day' => 20000,
                'allowed_roles' => null,
                'priority' => 90,
            ],
            [
                'name' => 'แบนเนอร์แจ้งเตือน',
                'path' => 'api/v1/app/banners',
                'method' => 'GET',
                'category' => 'App Configuration',
                'description' => 'ดึงแบนเนอร์แจ้งเตือน (public)',
                'is_active' => true,
                'requires_auth' => false,
                'rate_limit_per_minute' => 100,
                'rate_limit_per_hour' => 2000,
                'rate_limit_per_day' => 20000,
                'allowed_roles' => null,
                'priority' => 91,
            ],
            [
                'name' => 'บันทึกการดูแบนเนอร์',
                'path' => 'api/v1/app/banners/{appBanner}/view',
                'method' => 'POST',
                'category' => 'App Configuration',
                'description' => 'บันทึกการดูแบนเนอร์',
                'is_active' => true,
                'requires_auth' => false,
                'rate_limit_per_minute' => 100,
                'rate_limit_per_hour' => 2000,
                'rate_limit_per_day' => 20000,
                'allowed_roles' => null,
                'priority' => 92,
            ],
            [
                'name' => 'บันทึกการคลิกแบนเนอร์',
                'path' => 'api/v1/app/banners/{appBanner}/click',
                'method' => 'POST',
                'category' => 'App Configuration',
                'description' => 'บันทึกการคลิกแบนเนอร์',
                'is_active' => true,
                'requires_auth' => false,
                'rate_limit_per_minute' => 100,
                'rate_limit_per_hour' => 2000,
                'rate_limit_per_day' => 20000,
                'allowed_roles' => null,
                'priority' => 93,
            ],
            [
                'name' => 'การตั้งค่า App (ต้อง auth)',
                'path' => 'api/v1/app/config',
                'method' => 'GET',
                'category' => 'App Configuration',
                'description' => 'ดึงการตั้งค่า app สำหรับผู้ใช้ที่ login',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user', 'seller'],
                'priority' => 94,
            ],
            [
                'name' => 'การตั้งค่าทั่วไป',
                'path' => 'api/v1/app/settings',
                'method' => 'GET',
                'category' => 'App Configuration',
                'description' => 'ดึงการตั้งค่าทั่วไป',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user', 'seller'],
                'priority' => 95,
            ],
            [
                'name' => 'ธีม App',
                'path' => 'api/v1/app/theme',
                'method' => 'GET',
                'category' => 'App Configuration',
                'description' => 'ดึงธีม app',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user', 'seller'],
                'priority' => 96,
            ],
            [
                'name' => 'ธีมแบบเต็ม',
                'path' => 'api/v1/app/complete-theme',
                'method' => 'GET',
                'category' => 'App Configuration',
                'description' => 'ดึงธีมแบบเต็มรูปแบบ',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user', 'seller'],
                'priority' => 97,
            ],
            [
                'name' => 'ส่วนควบคุม',
                'path' => 'api/v1/app/control-sections',
                'method' => 'GET',
                'category' => 'App Configuration',
                'description' => 'ดึงส่วนควบคุม app',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user', 'seller'],
                'priority' => 98,
            ],
            [
                'name' => 'การตั้งค่าคอมโพเนนต์',
                'path' => 'api/v1/app/component-settings',
                'method' => 'GET',
                'category' => 'App Configuration',
                'description' => 'ดึงการตั้งค่าคอมโพเนนต์',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user', 'seller'],
                'priority' => 99,
            ],
            [
                'name' => 'ฟีเจอร์ App',
                'path' => 'api/v1/app/features',
                'method' => 'GET',
                'category' => 'App Configuration',
                'description' => 'ดึงฟีเจอร์ที่เปิดใช้งาน',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user', 'seller'],
                'priority' => 100,
            ],

            // ============================================
            // AI Gen - Image & Video Generation
            // ============================================
            [
                'name' => 'Dashboard AI Gen',
                'path' => 'api/v1/ai-gen/dashboard',
                'method' => 'GET',
                'category' => 'AI Gen',
                'description' => 'ดึงข้อมูล Dashboard สำหรับ AI Gen',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 110,
            ],
            [
                'name' => 'สร้างภาพ/วิดีโอด้วย AI',
                'path' => 'api/v1/ai-gen/generate',
                'method' => 'POST',
                'category' => 'AI Gen',
                'description' => 'สร้างภาพหรือวิดีโอด้วย AI',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 10,
                'rate_limit_per_hour' => 100,
                'rate_limit_per_day' => 500,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 111,
            ],
            [
                'name' => 'รายการสร้างของฉัน',
                'path' => 'api/v1/ai-gen/generations',
                'method' => 'GET',
                'category' => 'AI Gen',
                'description' => 'ดึงรายการสิ่งที่สร้างด้วย AI',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 112,
            ],
            [
                'name' => 'รายละเอียดการสร้าง',
                'path' => 'api/v1/ai-gen/generations/{generationId}',
                'method' => 'GET',
                'category' => 'AI Gen',
                'description' => 'ดึงรายละเอียดการสร้าง',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 113,
            ],
            [
                'name' => 'สถานะการสร้าง',
                'path' => 'api/v1/ai-gen/generations/{generationId}/status',
                'method' => 'GET',
                'category' => 'AI Gen',
                'description' => 'ตรวจสอบสถานะการสร้าง',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 100,
                'rate_limit_per_hour' => 2000,
                'rate_limit_per_day' => 20000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 114,
            ],
            [
                'name' => 'รายการโปรด AI Gen',
                'path' => 'api/v1/ai-gen/generations/{generationId}/favorite',
                'method' => 'POST',
                'category' => 'AI Gen',
                'description' => 'เพิ่ม/ลบรายการโปรด',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 30,
                'rate_limit_per_hour' => 500,
                'rate_limit_per_day' => 5000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 115,
            ],
            [
                'name' => 'ลบการสร้าง',
                'path' => 'api/v1/ai-gen/generations/{generationId}',
                'method' => 'DELETE',
                'category' => 'AI Gen',
                'description' => 'ลบการสร้างที่ไม่ต้องการ',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 30,
                'rate_limit_per_hour' => 300,
                'rate_limit_per_day' => 2000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 116,
            ],
            [
                'name' => 'แพ็คเกจ AI Gen',
                'path' => 'api/v1/ai-gen/packages',
                'method' => 'GET',
                'category' => 'AI Gen',
                'description' => 'ดึงรายการแพ็คเกจ AI Gen',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 117,
            ],
            [
                'name' => 'รายละเอียดแพ็คเกจ',
                'path' => 'api/v1/ai-gen/packages/{packageId}',
                'method' => 'GET',
                'category' => 'AI Gen',
                'description' => 'ดึงรายละเอียดแพ็คเกจ',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 118,
            ],
            [
                'name' => 'ซื้อแพ็คเกจ',
                'path' => 'api/v1/ai-gen/packages/{packageId}/purchase',
                'method' => 'POST',
                'category' => 'AI Gen',
                'description' => 'ซื้อแพ็คเกจ AI Gen',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 10,
                'rate_limit_per_hour' => 100,
                'rate_limit_per_day' => 500,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 119,
            ],

            // ============================================
            // Video Reward System
            // ============================================
            [
                'name' => 'Dashboard Video Rewards',
                'path' => 'api/v1/video-rewards/dashboard',
                'method' => 'GET',
                'category' => 'Video Rewards',
                'description' => 'ดึงข้อมูล Dashboard ระบบรางวัลวิดีโอ',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 120,
            ],
            [
                'name' => 'สถิติ Video Rewards',
                'path' => 'api/v1/video-rewards/statistics',
                'method' => 'GET',
                'category' => 'Video Rewards',
                'description' => 'ดึงสถิติระบบรางวัลวิดีโอ',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 121,
            ],
            [
                'name' => 'กระดานผู้นำวิดีโอ',
                'path' => 'api/v1/video-rewards/leaderboard',
                'method' => 'GET',
                'category' => 'Video Rewards',
                'description' => 'ดึงกระดานผู้นำระบบรางวัลวิดีโอ',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 122,
            ],
            [
                'name' => 'รายการช่อง',
                'path' => 'api/v1/video-rewards/channels',
                'method' => 'GET',
                'category' => 'Video Rewards',
                'description' => 'ดึงรายการช่องวิดีโอ',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 123,
            ],
            [
                'name' => 'วิดีโอในช่อง',
                'path' => 'api/v1/video-rewards/channels/{channelId}/videos',
                'method' => 'GET',
                'category' => 'Video Rewards',
                'description' => 'ดึงรายการวิดีโอในช่อง',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 124,
            ],
            [
                'name' => 'รายละเอียดวิดีโอ',
                'path' => 'api/v1/video-rewards/videos/{videoId}',
                'method' => 'GET',
                'category' => 'Video Rewards',
                'description' => 'ดึงรายละเอียดวิดีโอ',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 125,
            ],
            [
                'name' => 'เริ่มดูวิดีโอ',
                'path' => 'api/v1/video-rewards/watch/start',
                'method' => 'POST',
                'category' => 'Video Rewards',
                'description' => 'เริ่มต้นการดูวิดีโอ',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 30,
                'rate_limit_per_hour' => 500,
                'rate_limit_per_day' => 5000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 126,
            ],
            [
                'name' => 'Heartbeat ดูวิดีโอ',
                'path' => 'api/v1/video-rewards/watch/heartbeat',
                'method' => 'POST',
                'category' => 'Video Rewards',
                'description' => 'ส่งสัญญาณระหว่างดูวิดีโอ',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 100,
                'rate_limit_per_hour' => 2000,
                'rate_limit_per_day' => 20000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 127,
            ],
            [
                'name' => 'จบการดูวิดีโอ',
                'path' => 'api/v1/video-rewards/watch/end',
                'method' => 'POST',
                'category' => 'Video Rewards',
                'description' => 'จบการดูวิดีโอ',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 30,
                'rate_limit_per_hour' => 500,
                'rate_limit_per_day' => 5000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 128,
            ],
            [
                'name' => 'รับรางวัลวิดีโอ',
                'path' => 'api/v1/video-rewards/watch/claim-reward',
                'method' => 'POST',
                'category' => 'Video Rewards',
                'description' => 'รับรางวัลจากการดูวิดีโอ',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 30,
                'rate_limit_per_hour' => 500,
                'rate_limit_per_day' => 5000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 129,
            ],
            [
                'name' => 'รายการเควส',
                'path' => 'api/v1/video-rewards/quests',
                'method' => 'GET',
                'category' => 'Video Rewards',
                'description' => 'ดึงรายการเควส',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 130,
            ],
            [
                'name' => 'รายละเอียดเควส',
                'path' => 'api/v1/video-rewards/quests/{questId}',
                'method' => 'GET',
                'category' => 'Video Rewards',
                'description' => 'ดึงรายละเอียดเควส',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 131,
            ],
            [
                'name' => 'รับรางวัลเควส',
                'path' => 'api/v1/video-rewards/quests/{questId}/claim',
                'method' => 'POST',
                'category' => 'Video Rewards',
                'description' => 'รับรางวัลจากเควส',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 30,
                'rate_limit_per_hour' => 300,
                'rate_limit_per_day' => 2000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 132,
            ],
            [
                'name' => 'ประวัติเควส',
                'path' => 'api/v1/video-rewards/quests/history',
                'method' => 'GET',
                'category' => 'Video Rewards',
                'description' => 'ดึงประวัติการทำเควส',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 133,
            ],
            [
                'name' => 'อัตราแลกเปลี่ยนเหรียญ',
                'path' => 'api/v1/video-rewards/exchange/rates',
                'method' => 'GET',
                'category' => 'Video Rewards',
                'description' => 'ดึงอัตราแลกเปลี่ยนเหรียญ',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 134,
            ],
            [
                'name' => 'คำนวณการแลกเปลี่ยน',
                'path' => 'api/v1/video-rewards/exchange/calculate',
                'method' => 'POST',
                'category' => 'Video Rewards',
                'description' => 'คำนวณการแลกเปลี่ยนเหรียญ',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 135,
            ],
            [
                'name' => 'แลกเปลี่ยนเหรียญ',
                'path' => 'api/v1/video-rewards/exchange/request',
                'method' => 'POST',
                'category' => 'Video Rewards',
                'description' => 'ส่งคำขอแลกเปลี่ยนเหรียญ',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 10,
                'rate_limit_per_hour' => 100,
                'rate_limit_per_day' => 500,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 136,
            ],
            [
                'name' => 'ประวัติการแลกเปลี่ยน',
                'path' => 'api/v1/video-rewards/exchange/history',
                'method' => 'GET',
                'category' => 'Video Rewards',
                'description' => 'ดึงประวัติการแลกเปลี่ยนเหรียญ',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 137,
            ],
            [
                'name' => 'รายละเอียดคำขอแลกเปลี่ยน',
                'path' => 'api/v1/video-rewards/exchange/requests/{requestId}',
                'method' => 'GET',
                'category' => 'Video Rewards',
                'description' => 'ดึงรายละเอียดคำขอแลกเปลี่ยน',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 138,
            ],

            // ============================================
            // Viral Trend Detection
            // ============================================
            [
                'name' => 'Dashboard เทรนด์',
                'path' => 'api/v1/trends/dashboard',
                'method' => 'GET',
                'category' => 'Trends',
                'description' => 'ดึงข้อมูล Dashboard เทรนด์ไวรัล',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 140,
            ],
            [
                'name' => 'รายการเทรนด์',
                'path' => 'api/v1/trends',
                'method' => 'GET',
                'category' => 'Trends',
                'description' => 'ดึงรายการเทรนด์ทั้งหมด',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 141,
            ],
            [
                'name' => 'รายละเอียดเทรนด์',
                'path' => 'api/v1/trends/{trend}',
                'method' => 'GET',
                'category' => 'Trends',
                'description' => 'ดึงรายละเอียดเทรนด์',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 142,
            ],
            [
                'name' => 'สร้างคอนเทนต์จากเทรนด์',
                'path' => 'api/v1/trends/{trend}/generate-content',
                'method' => 'POST',
                'category' => 'Trends',
                'description' => 'สร้างคอนเทนต์จากเทรนด์ด้วย AI',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 10,
                'rate_limit_per_hour' => 100,
                'rate_limit_per_day' => 500,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 143,
            ],
            [
                'name' => 'คีย์เวิร์ดกำลังมาแรง',
                'path' => 'api/v1/trends/keywords/trending',
                'method' => 'GET',
                'category' => 'Trends',
                'description' => 'ดึงคีย์เวิร์ดที่กำลังมาแรง',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 144,
            ],
            [
                'name' => 'คีย์เวิร์ดกำลังโผล่',
                'path' => 'api/v1/trends/keywords/emerging',
                'method' => 'GET',
                'category' => 'Trends',
                'description' => 'ดึงคีย์เวิร์ดกำลังโผล่ขึ้น',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 145,
            ],
            [
                'name' => 'คีย์เวิร์ดที่เกี่ยวข้อง',
                'path' => 'api/v1/trends/keywords/{keyword}/related',
                'method' => 'GET',
                'category' => 'Trends',
                'description' => 'ดึงคีย์เวิร์ดที่เกี่ยวข้อง',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 146,
            ],
            [
                'name' => 'รายการแหล่งข้อมูล',
                'path' => 'api/v1/trends/sources',
                'method' => 'GET',
                'category' => 'Trends',
                'description' => 'ดึงรายการแหล่งข้อมูลเทรนด์',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 147,
            ],
            [
                'name' => 'สร้างแหล่งข้อมูล',
                'path' => 'api/v1/trends/sources',
                'method' => 'POST',
                'category' => 'Trends',
                'description' => 'สร้างแหล่งข้อมูลเทรนด์ใหม่',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 10,
                'rate_limit_per_hour' => 100,
                'rate_limit_per_day' => 500,
                'allowed_roles' => ['admin'],
                'priority' => 148,
            ],
            [
                'name' => 'แก้ไขแหล่งข้อมูล',
                'path' => 'api/v1/trends/sources/{source}',
                'method' => 'PUT',
                'category' => 'Trends',
                'description' => 'แก้ไขแหล่งข้อมูลเทรนด์',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 10,
                'rate_limit_per_hour' => 100,
                'rate_limit_per_day' => 500,
                'allowed_roles' => ['admin'],
                'priority' => 149,
            ],
            [
                'name' => 'ลบแหล่งข้อมูล',
                'path' => 'api/v1/trends/sources/{source}',
                'method' => 'DELETE',
                'category' => 'Trends',
                'description' => 'ลบแหล่งข้อมูลเทรนด์',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 10,
                'rate_limit_per_hour' => 100,
                'rate_limit_per_day' => 500,
                'allowed_roles' => ['admin'],
                'priority' => 150,
            ],
            [
                'name' => 'สถิติเทรนด์',
                'path' => 'api/v1/trends/analytics',
                'method' => 'GET',
                'category' => 'Trends',
                'description' => 'ดึงสถิติและวิเคราะห์เทรนด์',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 151,
            ],

            // ============================================
            // LINE Analytics
            // ============================================
            [
                'name' => 'Dashboard LINE Analytics',
                'path' => 'api/v1/line-analytics/dashboard',
                'method' => 'GET',
                'category' => 'LINE Analytics',
                'description' => 'ดึงข้อมูล Dashboard LINE Analytics',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 160,
            ],
            [
                'name' => 'สถิติ LINE',
                'path' => 'api/v1/line-analytics/stats',
                'method' => 'GET',
                'category' => 'LINE Analytics',
                'description' => 'ดึงสถิติ LINE OA ทั้งหมด',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 161,
            ],
            [
                'name' => 'Conversion Funnel',
                'path' => 'api/v1/line-analytics/funnel',
                'method' => 'GET',
                'category' => 'LINE Analytics',
                'description' => 'ดึงข้อมูล Conversion Funnel',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 162,
            ],
            [
                'name' => 'วิเคราะห์ Dropout',
                'path' => 'api/v1/line-analytics/dropout',
                'method' => 'GET',
                'category' => 'LINE Analytics',
                'description' => 'วิเคราะห์ Dropout ในกระบวนการสมัคร',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 163,
            ],
            [
                'name' => 'เทรนด์การสมัคร',
                'path' => 'api/v1/line-analytics/trends',
                'method' => 'GET',
                'category' => 'LINE Analytics',
                'description' => 'ดึงเทรนด์การสมัครสมาชิก',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 164,
            ],
            [
                'name' => 'กระดานผู้นำ LINE',
                'path' => 'api/v1/line-analytics/leaderboard',
                'method' => 'GET',
                'category' => 'LINE Analytics',
                'description' => 'ดึงกระดานผู้นำจากข้อมูล LINE',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 165,
            ],
            [
                'name' => 'การสนทนาที่กำลังดำเนินการ',
                'path' => 'api/v1/line-analytics/active',
                'method' => 'GET',
                'category' => 'LINE Analytics',
                'description' => 'ดึงการสนทนาที่กำลังดำเนินการ',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 166,
            ],
            [
                'name' => 'ส่งออกข้อมูล LINE',
                'path' => 'api/v1/line-analytics/export',
                'method' => 'GET',
                'category' => 'LINE Analytics',
                'description' => 'ส่งออกข้อมูล LINE Analytics',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 10,
                'rate_limit_per_hour' => 50,
                'rate_limit_per_day' => 200,
                'allowed_roles' => ['admin'],
                'priority' => 167,
            ],
            [
                'name' => 'สถิติ Sponsor',
                'path' => 'api/v1/line-analytics/sponsor/{sponsorId}',
                'method' => 'GET',
                'category' => 'LINE Analytics',
                'description' => 'ดึงสถิติ Sponsor เฉพาะ',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 168,
            ],
            [
                'name' => 'ล้างแคช LINE Analytics',
                'path' => 'api/v1/line-analytics/clear-cache',
                'method' => 'POST',
                'category' => 'LINE Analytics',
                'description' => 'ล้างแคช LINE Analytics',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 5,
                'rate_limit_per_hour' => 20,
                'rate_limit_per_day' => 100,
                'allowed_roles' => ['admin'],
                'priority' => 169,
            ],

            // ============================================
            // Taskbar Shortcuts
            // ============================================
            [
                'name' => 'รายการ Shortcuts',
                'path' => 'api/v1/taskbar-shortcuts',
                'method' => 'GET',
                'category' => 'Taskbar',
                'description' => 'ดึงรายการ Taskbar Shortcuts',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 60,
                'rate_limit_per_hour' => 1000,
                'rate_limit_per_day' => 10000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 170,
            ],
            [
                'name' => 'สร้าง Shortcut',
                'path' => 'api/v1/taskbar-shortcuts',
                'method' => 'POST',
                'category' => 'Taskbar',
                'description' => 'สร้าง Taskbar Shortcut ใหม่',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 30,
                'rate_limit_per_hour' => 300,
                'rate_limit_per_day' => 2000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 171,
            ],
            [
                'name' => 'ลบ Shortcut',
                'path' => 'api/v1/taskbar-shortcuts/{id}',
                'method' => 'DELETE',
                'category' => 'Taskbar',
                'description' => 'ลบ Taskbar Shortcut',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 30,
                'rate_limit_per_hour' => 300,
                'rate_limit_per_day' => 2000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 172,
            ],
            [
                'name' => 'จัดเรียง Shortcuts',
                'path' => 'api/v1/taskbar-shortcuts/reorder',
                'method' => 'POST',
                'category' => 'Taskbar',
                'description' => 'จัดเรียง Taskbar Shortcuts',
                'is_active' => true,
                'requires_auth' => true,
                'rate_limit_per_minute' => 30,
                'rate_limit_per_hour' => 300,
                'rate_limit_per_day' => 2000,
                'allowed_roles' => ['admin', 'user'],
                'priority' => 173,
            ],

            // ============================================
            // Cookie Consent (Public)
            // ============================================
            [
                'name' => 'บันทึก Cookie Consent',
                'path' => 'api/cookie-consent',
                'method' => 'POST',
                'category' => 'Cookie',
                'description' => 'บันทึกการยินยอม Cookie (public)',
                'is_active' => true,
                'requires_auth' => false,
                'rate_limit_per_minute' => 30,
                'rate_limit_per_hour' => 300,
                'rate_limit_per_day' => 2000,
                'allowed_roles' => null,
                'priority' => 180,
            ],
            [
                'name' => 'ดึง Cookie Consent',
                'path' => 'api/cookie-consent',
                'method' => 'GET',
                'category' => 'Cookie',
                'description' => 'ดึงข้อมูลการยินยอม Cookie',
                'is_active' => true,
                'requires_auth' => false,
                'rate_limit_per_minute' => 100,
                'rate_limit_per_hour' => 2000,
                'rate_limit_per_day' => 20000,
                'allowed_roles' => null,
                'priority' => 181,
            ],
            [
                'name' => 'ติดตามหน้าเว็บ',
                'path' => 'api/cookie-track-page',
                'method' => 'POST',
                'category' => 'Cookie',
                'description' => 'ติดตามการเข้าชมหน้าเว็บ',
                'is_active' => true,
                'requires_auth' => false,
                'rate_limit_per_minute' => 100,
                'rate_limit_per_hour' => 2000,
                'rate_limit_per_day' => 20000,
                'allowed_roles' => null,
                'priority' => 182,
            ],
            [
                'name' => 'ติดตามคีย์เวิร์ด',
                'path' => 'api/cookie-track-keyword',
                'method' => 'POST',
                'category' => 'Cookie',
                'description' => 'ติดตามคีย์เวิร์ดที่ค้นหา',
                'is_active' => true,
                'requires_auth' => false,
                'rate_limit_per_minute' => 100,
                'rate_limit_per_hour' => 2000,
                'rate_limit_per_day' => 20000,
                'allowed_roles' => null,
                'priority' => 183,
            ],
            [
                'name' => 'ติดตามสินค้า',
                'path' => 'api/cookie-track-product',
                'method' => 'POST',
                'category' => 'Cookie',
                'description' => 'ติดตามสินค้าที่ดู',
                'is_active' => true,
                'requires_auth' => false,
                'rate_limit_per_minute' => 100,
                'rate_limit_per_hour' => 2000,
                'rate_limit_per_day' => 20000,
                'allowed_roles' => null,
                'priority' => 184,
            ],
        ];

        foreach ($endpoints as $endpoint) {
            ApiEndpoint::updateOrCreate(
                [
                    'path' => $endpoint['path'],
                    'method' => $endpoint['method'],
                ],
                $endpoint
            );
        }

        $this->command->info('✓ สร้างข้อมูล API endpoints เรียบร้อยแล้ว: ' . count($endpoints) . ' endpoints');
    }
}
