<?php

namespace Database\Seeders;

use App\Models\HoroscopeZodiacSign;
use Illuminate\Database\Seeder;

/**
 * สร้างข้อมูล 12 ราศีไทย/สากล
 *
 * ข้อมูลครบ: ชื่อไทย/อังกฤษ, ช่วงวันที่, ธาตุ, ดาวเคราะห์, สัญลักษณ์, สี
 * คำอธิบาย, บุคลิกภาพ, จุดแข็ง, จุดอ่อน
 */
class HoroscopeZodiacSignSeeder extends Seeder
{
    /**
     * สร้างข้อมูล 12 ราศี
     *
     * @return void
     */
    public function run(): void
    {
        $this->command->info('🌟 กำลัง seed ข้อมูล 12 ราศี...');

        if (HoroscopeZodiacSign::count() >= 12) {
            $this->command->info('ข้อมูล 12 ราศีมีอยู่แล้ว ข้าม...');

            return;
        }

        $zodiacSigns = [
            [
                'name_th' => 'ราศีเมษ',
                'name_en' => 'Aries',
                'slug' => 'aries',
                'date_range_start' => '03-21',
                'date_range_end' => '04-19',
                'date_range_display_th' => '21 มี.ค. - 19 เม.ย.',
                'element' => 'ไฟ',
                'ruling_planet' => 'Mars (อังคาร)',
                'quality' => 'Cardinal',
                'symbol_emoji' => '♈',
                'color_hex' => '#ef4444',
                'gradient_from' => '#ef4444',
                'gradient_to' => '#f97316',
                'description_th' => 'ราศีเมษเป็นราศีแรกของจักรราศี เป็นตัวแทนของการเริ่มต้นใหม่ ความกล้าหาญ และความเป็นผู้นำ',
                'personality_th' => 'กล้าหาญ มีความเป็นผู้นำ กระตือรือร้น ตรงไปตรงมา ชอบความท้าทาย',
                'strengths_th' => 'กล้าตัดสินใจ มีพลังงาน ซื่อสัตย์ มั่นใจในตัวเอง',
                'weaknesses_th' => 'ใจร้อน ขี้โมโห ชอบแข่งขัน บางครั้งประมาท',
                'sort_order' => 1,
            ],
            [
                'name_th' => 'ราศีพฤษภ',
                'name_en' => 'Taurus',
                'slug' => 'taurus',
                'date_range_start' => '04-20',
                'date_range_end' => '05-20',
                'date_range_display_th' => '20 เม.ย. - 20 พ.ค.',
                'element' => 'ดิน',
                'ruling_planet' => 'Venus (ศุกร์)',
                'quality' => 'Fixed',
                'symbol_emoji' => '♉',
                'color_hex' => '#22c55e',
                'gradient_from' => '#22c55e',
                'gradient_to' => '#10b981',
                'description_th' => 'ราศีพฤษภเป็นตัวแทนของความมั่นคง ความอดทน และความรักในความสวยงาม',
                'personality_th' => 'อดทน มั่นคง รักความสงบ ชอบความสวยงาม รักครอบครัว',
                'strengths_th' => 'อดทน ซื่อสัตย์ มีเสถียรภาพ ปฏิบัติจริง',
                'weaknesses_th' => 'ดื้อ หวงของ ไม่ชอบการเปลี่ยนแปลง',
                'sort_order' => 2,
            ],
            [
                'name_th' => 'ราศีเมถุน',
                'name_en' => 'Gemini',
                'slug' => 'gemini',
                'date_range_start' => '05-21',
                'date_range_end' => '06-20',
                'date_range_display_th' => '21 พ.ค. - 20 มิ.ย.',
                'element' => 'ลม',
                'ruling_planet' => 'Mercury (พุธ)',
                'quality' => 'Mutable',
                'symbol_emoji' => '♊',
                'color_hex' => '#eab308',
                'gradient_from' => '#eab308',
                'gradient_to' => '#f59e0b',
                'description_th' => 'ราศีเมถุนเป็นตัวแทนของความฉลาด การสื่อสาร และความอยากรู้อยากเห็น',
                'personality_th' => 'ฉลาด ช่างพูด ปรับตัวเก่ง อยากรู้อยากเห็น มีเสน่ห์',
                'strengths_th' => 'สื่อสารเก่ง เรียนรู้เร็ว ปรับตัวได้ดี มีอารมณ์ขัน',
                'weaknesses_th' => 'เปลี่ยนใจง่าย กระสับกระส่าย ไม่ค่อยจริงจัง',
                'sort_order' => 3,
            ],
            [
                'name_th' => 'ราศีกรกฎ',
                'name_en' => 'Cancer',
                'slug' => 'cancer',
                'date_range_start' => '06-21',
                'date_range_end' => '07-22',
                'date_range_display_th' => '21 มิ.ย. - 22 ก.ค.',
                'element' => 'น้ำ',
                'ruling_planet' => 'Moon (จันทร์)',
                'quality' => 'Cardinal',
                'symbol_emoji' => '♋',
                'color_hex' => '#64748b',
                'gradient_from' => '#64748b',
                'gradient_to' => '#94a3b8',
                'description_th' => 'ราศีกรกฎเป็นตัวแทนของความรักครอบครัว ความอ่อนโยน และสัญชาตญาณ',
                'personality_th' => 'อ่อนโยน รักครอบครัว มีสัญชาตญาณดี ห่วงใยคนรอบข้าง',
                'strengths_th' => 'เห็นอกเห็นใจ ซื่อสัตย์ รักครอบครัว สัญชาตญาณแม่นยำ',
                'weaknesses_th' => 'อารมณ์อ่อนไหว ขี้น้อยใจ หวงแหน',
                'sort_order' => 4,
            ],
            [
                'name_th' => 'ราศีสิงห์',
                'name_en' => 'Leo',
                'slug' => 'leo',
                'date_range_start' => '07-23',
                'date_range_end' => '08-22',
                'date_range_display_th' => '23 ก.ค. - 22 ส.ค.',
                'element' => 'ไฟ',
                'ruling_planet' => 'Sun (อาทิตย์)',
                'quality' => 'Fixed',
                'symbol_emoji' => '♌',
                'color_hex' => '#f97316',
                'gradient_from' => '#f97316',
                'gradient_to' => '#eab308',
                'description_th' => 'ราศีสิงห์เป็นตัวแทนของความเป็นผู้นำ ความมั่นใจ และความใจกว้าง',
                'personality_th' => 'มั่นใจ เป็นผู้นำ ใจกว้าง รักเกียรติ ชอบเป็นจุดเด่น',
                'strengths_th' => 'เป็นผู้นำ ใจกว้าง สร้างสรรค์ กล้าหาญ',
                'weaknesses_th' => 'หยิ่ง ชอบควบคุม ต้องการความสนใจ',
                'sort_order' => 5,
            ],
            [
                'name_th' => 'ราศีกันย์',
                'name_en' => 'Virgo',
                'slug' => 'virgo',
                'date_range_start' => '08-23',
                'date_range_end' => '09-22',
                'date_range_display_th' => '23 ส.ค. - 22 ก.ย.',
                'element' => 'ดิน',
                'ruling_planet' => 'Mercury (พุธ)',
                'quality' => 'Mutable',
                'symbol_emoji' => '♍',
                'color_hex' => '#84cc16',
                'gradient_from' => '#84cc16',
                'gradient_to' => '#22c55e',
                'description_th' => 'ราศีกันย์เป็นตัวแทนของความละเอียดรอบคอบ ความอุตสาหะ และการรับใช้ผู้อื่น',
                'personality_th' => 'ละเอียด รอบคอบ ขยัน มีระเบียบ ชอบช่วยเหลือผู้อื่น',
                'strengths_th' => 'ละเอียดรอบคอบ ขยัน มีระเบียบ วิเคราะห์เก่ง',
                'weaknesses_th' => 'จู้จี้ วิตกกังวล จับผิดเก่ง เรียกร้องสูง',
                'sort_order' => 6,
            ],
            [
                'name_th' => 'ราศีตุลย์',
                'name_en' => 'Libra',
                'slug' => 'libra',
                'date_range_start' => '09-23',
                'date_range_end' => '10-22',
                'date_range_display_th' => '23 ก.ย. - 22 ต.ค.',
                'element' => 'ลม',
                'ruling_planet' => 'Venus (ศุกร์)',
                'quality' => 'Cardinal',
                'symbol_emoji' => '♎',
                'color_hex' => '#ec4899',
                'gradient_from' => '#ec4899',
                'gradient_to' => '#f472b6',
                'description_th' => 'ราศีตุลย์เป็นตัวแทนของความสมดุล ความยุติธรรม และความงาม',
                'personality_th' => 'รักความยุติธรรม มีเสน่ห์ ชอบความสมดุล มีทักษะสังคม',
                'strengths_th' => 'ยุติธรรม มีเสน่ห์ เจรจาเก่ง มีรสนิยม',
                'weaknesses_th' => 'ลังเลใจ หลีกเลี่ยงความขัดแย้ง ต้องการความเห็นชอบ',
                'sort_order' => 7,
            ],
            [
                'name_th' => 'ราศีพิจิก',
                'name_en' => 'Scorpio',
                'slug' => 'scorpio',
                'date_range_start' => '10-23',
                'date_range_end' => '11-21',
                'date_range_display_th' => '23 ต.ค. - 21 พ.ย.',
                'element' => 'น้ำ',
                'ruling_planet' => 'Pluto (พลูโต)',
                'quality' => 'Fixed',
                'symbol_emoji' => '♏',
                'color_hex' => '#7c3aed',
                'gradient_from' => '#7c3aed',
                'gradient_to' => '#a855f7',
                'description_th' => 'ราศีพิจิกเป็นตัวแทนของความเข้มข้น ความลึกลับ และพลังการเปลี่ยนแปลง',
                'personality_th' => 'เข้มข้น ลึกลับ มุ่งมั่น ซื่อสัตย์ มีพลังดึงดูด',
                'strengths_th' => 'มุ่งมั่น ซื่อสัตย์ กล้าหาญ หยั่งรู้',
                'weaknesses_th' => 'หึงหวง ลึกลับ อาฆาต ครอบงำ',
                'sort_order' => 8,
            ],
            [
                'name_th' => 'ราศีธนู',
                'name_en' => 'Sagittarius',
                'slug' => 'sagittarius',
                'date_range_start' => '11-22',
                'date_range_end' => '12-21',
                'date_range_display_th' => '22 พ.ย. - 21 ธ.ค.',
                'element' => 'ไฟ',
                'ruling_planet' => 'Jupiter (พฤหัสบดี)',
                'quality' => 'Mutable',
                'symbol_emoji' => '♐',
                'color_hex' => '#8b5cf6',
                'gradient_from' => '#8b5cf6',
                'gradient_to' => '#6366f1',
                'description_th' => 'ราศีธนูเป็นตัวแทนของการผจญภัย ความอิสระ และปรัชญา',
                'personality_th' => 'รักอิสระ ชอบผจญภัย มองโลกในแง่ดี ตรงไปตรงมา',
                'strengths_th' => 'มองโลกในแง่ดี กล้าหาญ ใจกว้าง อารมณ์ดี',
                'weaknesses_th' => 'ไม่อดทน พูดตรงเกิน ขาดความรับผิดชอบ',
                'sort_order' => 9,
            ],
            [
                'name_th' => 'ราศีมังกร',
                'name_en' => 'Capricorn',
                'slug' => 'capricorn',
                'date_range_start' => '12-22',
                'date_range_end' => '01-19',
                'date_range_display_th' => '22 ธ.ค. - 19 ม.ค.',
                'element' => 'ดิน',
                'ruling_planet' => 'Saturn (เสาร์)',
                'quality' => 'Cardinal',
                'symbol_emoji' => '♑',
                'color_hex' => '#374151',
                'gradient_from' => '#374151',
                'gradient_to' => '#6b7280',
                'description_th' => 'ราศีมังกรเป็นตัวแทนของความทะเยอทะยาน วินัย และความรับผิดชอบ',
                'personality_th' => 'ทะเยอทะยาน มีวินัย รับผิดชอบ อดทน มุ่งมั่นสู่เป้าหมาย',
                'strengths_th' => 'มีวินัย รับผิดชอบ อดทน วางแผนเก่ง',
                'weaknesses_th' => 'เข้มงวด ทำงานหนักเกิน มองโลกในแง่ร้าย',
                'sort_order' => 10,
            ],
            [
                'name_th' => 'ราศีกุมภ์',
                'name_en' => 'Aquarius',
                'slug' => 'aquarius',
                'date_range_start' => '01-20',
                'date_range_end' => '02-18',
                'date_range_display_th' => '20 ม.ค. - 18 ก.พ.',
                'element' => 'ลม',
                'ruling_planet' => 'Uranus (มฤตยู)',
                'quality' => 'Fixed',
                'symbol_emoji' => '♒',
                'color_hex' => '#06b6d4',
                'gradient_from' => '#06b6d4',
                'gradient_to' => '#0ea5e9',
                'description_th' => 'ราศีกุมภ์เป็นตัวแทนของนวัตกรรม ความเป็นตัวของตัวเอง และมนุษยธรรม',
                'personality_th' => 'มีความคิดสร้างสรรค์ เป็นตัวของตัวเอง รักอิสระ มีมนุษยธรรม',
                'strengths_th' => 'สร้างสรรค์ เป็นตัวของตัวเอง มีวิสัยทัศน์ มนุษยธรรม',
                'weaknesses_th' => 'แปลกประหลาด ห่างเหิน ดื้อรั้น ไม่แสดงอารมณ์',
                'sort_order' => 11,
            ],
            [
                'name_th' => 'ราศีมีน',
                'name_en' => 'Pisces',
                'slug' => 'pisces',
                'date_range_start' => '02-19',
                'date_range_end' => '03-20',
                'date_range_display_th' => '19 ก.พ. - 20 มี.ค.',
                'element' => 'น้ำ',
                'ruling_planet' => 'Neptune (เนปจูน)',
                'quality' => 'Mutable',
                'symbol_emoji' => '♓',
                'color_hex' => '#3b82f6',
                'gradient_from' => '#3b82f6',
                'gradient_to' => '#8b5cf6',
                'description_th' => 'ราศีมีนเป็นตัวแทนของจินตนาการ ความเห็นอกเห็นใจ และจิตวิญญาณ',
                'personality_th' => 'จินตนาการสูง เห็นอกเห็นใจ สร้างสรรค์ ลึกซึ้ง อ่อนโยน',
                'strengths_th' => 'เห็นอกเห็นใจ สร้างสรรค์ หยั่งรู้ ใจดี',
                'weaknesses_th' => 'อ่อนไหวเกิน หนีปัญหา ไม่ชัดเจน ถูกหลอกง่าย',
                'sort_order' => 12,
            ],
        ];

        foreach ($zodiacSigns as $sign) {
            HoroscopeZodiacSign::updateOrCreate(
                ['slug' => $sign['slug']],
                $sign
            );
        }

        $this->command->info('✅ Seed ข้อมูล 12 ราศี สำเร็จ!');
    }
}
