<?php

namespace Database\Seeders;

use App\Models\HuggingFaceTrendingModel;
use Illuminate\Database\Seeder;

/**
 * Seeder สำหรับ Trending Models จาก Hugging Face
 *
 * สร้างข้อมูล trending models ยอดนิยม พร้อมรายละเอียดครบถ้วน
 */
class HuggingFaceTrendingModelsSeeder extends Seeder
{
    /**
     * สร้างข้อมูล trending models
     *
     * @return void
     */
    public function run(): void
    {
        $this->command->info('🌱 กำลัง seed Trending Models จาก Hugging Face...');

        // ✅ ตรวจสอบก่อนสร้าง (idempotent)
        if (HuggingFaceTrendingModel::count() > 0) {
            $this->command->info('ข้อมูล Trending Models มีอยู่แล้ว ข้าม...');
            return;
        }

        $models = [
            // 🎨 Image Generation Models
            [
                'model_id' => 'black-forest-labs/FLUX.1-dev',
                'model_name' => 'FLUX.1 [dev]',
                'description' => '12 billion parameter rectified flow transformer สำหรับสร้างภาพคุณภาพสูง ความละเอียดสูงสุด มีความสามารถเหนือกว่า Midjourney, DALL-E 3, และ Stable Diffusion 3',
                'task' => 'text-to-image',
                'library' => 'diffusers',
                'tags' => ['text-to-image', 'flux', 'diffusers', 'image-generation', 'high-quality'],
                'pipeline_tag' => ['text-to-image'],
                'author' => 'Black Forest Labs',
                'organization' => 'black-forest-labs',
                'downloads' => 2500000,
                'downloads_last_month' => 850000,
                'likes' => 15420,
                'trending_score' => 95,
                'model_size' => '23.8 GB',
                'model_size_bytes' => 25547038310,
                'supported_languages' => ['en', 'th', 'multilingual'],
                'license' => 'flux-1-dev-non-commercial-license',
                'min_gpu_memory' => '24 GB',
                'recommended_gpu' => 'NVIDIA A100 40GB, RTX 4090, RTX 3090',
                'hardware_requirements' => [
                    'min_vram' => '24 GB',
                    'recommended_vram' => '40 GB',
                    'min_ram' => '32 GB',
                    'storage' => '30 GB',
                ],
                'benchmark_scores' => [
                    'quality' => 9.5,
                    'prompt_adherence' => 9.8,
                    'speed' => 7.5,
                    'fidelity' => 9.7,
                ],
                'avg_inference_time_ms' => 8500.00,
                'performance_tier' => 'premium',
                'model_url' => 'https://huggingface.co/black-forest-labs/FLUX.1-dev',
                'paper_url' => null,
                'demo_url' => 'https://huggingface.co/spaces/black-forest-labs/FLUX.1-dev',
                'documentation_url' => 'https://huggingface.co/black-forest-labs/FLUX.1-dev#usage',
                'supports_inference_api' => true,
                'supports_spaces' => true,
                'can_run_locally' => true,
                'compatible_cloud_providers' => ['runpod', 'vast-ai', 'lambda-labs', 'paperspace'],
                'estimated_cost_per_hour' => 1.50,
                'rank_overall' => 1,
                'rank_in_category' => 1,
                'category' => 'Image Generation',
                'is_featured' => true,
                'is_recommended' => false,
                'is_production_ready' => true,
                'difficulty_level' => 'advanced',
                'first_seen_at' => now()->subDays(45),
                'last_updated_at' => now()->subDays(3),
                'featured_at' => now()->subDays(30),
            ],
            [
                'model_id' => 'stabilityai/stable-diffusion-3.5-large',
                'model_name' => 'Stable Diffusion 3.5 Large',
                'description' => 'รุ่นล่าสุดของ Stable Diffusion ขนาด 8 billion parameters พัฒนาคุณภาพภาพและความเข้าใจ prompt ดีขึ้นมาก รองรับ 1 megapixel',
                'task' => 'text-to-image',
                'library' => 'diffusers',
                'tags' => ['text-to-image', 'stable-diffusion', 'sd3', 'image-generation'],
                'pipeline_tag' => ['text-to-image'],
                'author' => 'Stability AI',
                'organization' => 'stabilityai',
                'downloads' => 3200000,
                'downloads_last_month' => 920000,
                'likes' => 18500,
                'trending_score' => 92,
                'model_size' => '11.9 GB',
                'model_size_bytes' => 12780085248,
                'supported_languages' => ['en', 'multilingual'],
                'license' => 'stability-ai-community',
                'min_gpu_memory' => '16 GB',
                'recommended_gpu' => 'NVIDIA RTX 4090, RTX 3090, A100',
                'hardware_requirements' => [
                    'min_vram' => '16 GB',
                    'recommended_vram' => '24 GB',
                    'min_ram' => '32 GB',
                    'storage' => '15 GB',
                ],
                'benchmark_scores' => [
                    'quality' => 9.2,
                    'prompt_adherence' => 9.4,
                    'speed' => 8.0,
                    'fidelity' => 9.3,
                ],
                'avg_inference_time_ms' => 6800.00,
                'performance_tier' => 'premium',
                'model_url' => 'https://huggingface.co/stabilityai/stable-diffusion-3.5-large',
                'paper_url' => 'https://stability.ai/research/stable-diffusion-3',
                'demo_url' => 'https://huggingface.co/spaces/stabilityai/stable-diffusion-3.5-large',
                'documentation_url' => 'https://huggingface.co/stabilityai/stable-diffusion-3.5-large',
                'supports_inference_api' => true,
                'supports_spaces' => true,
                'can_run_locally' => true,
                'compatible_cloud_providers' => ['runpod', 'vast-ai', 'lambda-labs', 'google-colab'],
                'estimated_cost_per_hour' => 0.80,
                'rank_overall' => 2,
                'rank_in_category' => 2,
                'category' => 'Image Generation',
                'is_featured' => true,
                'is_recommended' => true,
                'is_production_ready' => true,
                'difficulty_level' => 'intermediate',
                'first_seen_at' => now()->subDays(60),
                'last_updated_at' => now()->subDays(5),
                'featured_at' => now()->subDays(45),
            ],

            // 🤖 Language Models (LLMs)
            [
                'model_id' => 'meta-llama/Llama-3.1-405B-Instruct',
                'model_name' => 'Llama 3.1 405B Instruct',
                'description' => 'โมเดลภาษาขนาดใหญ่ที่สุดจาก Meta ขนาด 405 billion parameters รองรับ context length สูงสุด 128K tokens เทียบเท่า GPT-4',
                'task' => 'text-generation',
                'library' => 'transformers',
                'tags' => ['text-generation', 'llama', 'meta', 'instruction-following', 'conversational'],
                'pipeline_tag' => ['text-generation', 'conversational'],
                'author' => 'Meta',
                'organization' => 'meta-llama',
                'downloads' => 1850000,
                'downloads_last_month' => 680000,
                'likes' => 12300,
                'trending_score' => 88,
                'model_size' => '810 GB',
                'model_size_bytes' => 869921587200,
                'supported_languages' => ['en', 'th', 'multilingual'],
                'license' => 'llama3.1',
                'min_gpu_memory' => '200 GB',
                'recommended_gpu' => '8x NVIDIA A100 80GB, 4x H100',
                'hardware_requirements' => [
                    'min_vram' => '200 GB',
                    'recommended_vram' => '320 GB',
                    'min_ram' => '512 GB',
                    'storage' => '850 GB',
                ],
                'benchmark_scores' => [
                    'mmlu' => 88.6,
                    'gsm8k' => 95.1,
                    'humaneval' => 89.0,
                    'math' => 73.8,
                ],
                'avg_inference_time_ms' => 2500.00,
                'performance_tier' => 'enterprise',
                'model_url' => 'https://huggingface.co/meta-llama/Llama-3.1-405B-Instruct',
                'paper_url' => 'https://ai.meta.com/blog/meta-llama-3-1/',
                'demo_url' => null,
                'documentation_url' => 'https://huggingface.co/meta-llama/Llama-3.1-405B-Instruct',
                'supports_inference_api' => true,
                'supports_spaces' => false,
                'can_run_locally' => false,
                'compatible_cloud_providers' => ['runpod', 'lambda-labs', 'paperspace'],
                'estimated_cost_per_hour' => 25.00,
                'rank_overall' => 3,
                'rank_in_category' => 1,
                'category' => 'Language Model',
                'is_featured' => true,
                'is_recommended' => false,
                'is_production_ready' => true,
                'difficulty_level' => 'expert',
                'first_seen_at' => now()->subDays(90),
                'last_updated_at' => now()->subDays(7),
                'featured_at' => now()->subDays(75),
            ],
            [
                'model_id' => 'mistralai/Mixtral-8x7B-Instruct-v0.1',
                'model_name' => 'Mixtral 8x7B Instruct',
                'description' => 'Sparse Mixture of Experts model ขนาด 46.7B parameters ประสิทธิภาพใกล้เคียง GPT-3.5 Turbo แต่ใช้ทรัพยากรน้อยกว่ามาก รองรับ 32K context',
                'task' => 'text-generation',
                'library' => 'transformers',
                'tags' => ['text-generation', 'mixtral', 'mixture-of-experts', 'instruct', 'multilingual'],
                'pipeline_tag' => ['text-generation'],
                'author' => 'Mistral AI',
                'organization' => 'mistralai',
                'downloads' => 2100000,
                'downloads_last_month' => 750000,
                'likes' => 14200,
                'trending_score' => 86,
                'model_size' => '93.4 GB',
                'model_size_bytes' => 100278681600,
                'supported_languages' => ['en', 'fr', 'es', 'de', 'it', 'multilingual'],
                'license' => 'apache-2.0',
                'min_gpu_memory' => '48 GB',
                'recommended_gpu' => 'NVIDIA A100 80GB, 2x RTX 4090',
                'hardware_requirements' => [
                    'min_vram' => '48 GB',
                    'recommended_vram' => '80 GB',
                    'min_ram' => '128 GB',
                    'storage' => '100 GB',
                ],
                'benchmark_scores' => [
                    'mmlu' => 70.6,
                    'gsm8k' => 74.4,
                    'humaneval' => 40.2,
                    'arc' => 85.8,
                ],
                'avg_inference_time_ms' => 1200.00,
                'performance_tier' => 'premium',
                'model_url' => 'https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1',
                'paper_url' => 'https://arxiv.org/abs/2401.04088',
                'demo_url' => 'https://huggingface.co/spaces/mistralai/mixtral-8x7b-instruct',
                'documentation_url' => 'https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1',
                'supports_inference_api' => true,
                'supports_spaces' => true,
                'can_run_locally' => true,
                'compatible_cloud_providers' => ['runpod', 'vast-ai', 'lambda-labs', 'google-colab'],
                'estimated_cost_per_hour' => 2.50,
                'rank_overall' => 5,
                'rank_in_category' => 2,
                'category' => 'Language Model',
                'is_featured' => true,
                'is_recommended' => true,
                'is_production_ready' => true,
                'difficulty_level' => 'intermediate',
                'first_seen_at' => now()->subDays(120),
                'last_updated_at' => now()->subDays(10),
                'featured_at' => now()->subDays(100),
            ],

            // 🎵 Audio & Speech Models
            [
                'model_id' => 'openai/whisper-large-v3',
                'model_name' => 'Whisper Large V3',
                'description' => 'โมเดล Speech-to-Text ที่แม่นยำที่สุดจาก OpenAI รองรับ 99 ภาษา รวมภาษาไทย ความแม่นยำสูงมาก',
                'task' => 'automatic-speech-recognition',
                'library' => 'transformers',
                'tags' => ['automatic-speech-recognition', 'whisper', 'audio', 'speech-to-text', 'multilingual'],
                'pipeline_tag' => ['automatic-speech-recognition'],
                'author' => 'OpenAI',
                'organization' => 'openai',
                'downloads' => 5800000,
                'downloads_last_month' => 1200000,
                'likes' => 22000,
                'trending_score' => 94,
                'model_size' => '3.1 GB',
                'model_size_bytes' => 3328599040,
                'supported_languages' => ['en', 'th', 'multilingual'],
                'license' => 'apache-2.0',
                'min_gpu_memory' => '10 GB',
                'recommended_gpu' => 'NVIDIA RTX 3090, RTX 4080, T4',
                'hardware_requirements' => [
                    'min_vram' => '10 GB',
                    'recommended_vram' => '16 GB',
                    'min_ram' => '16 GB',
                    'storage' => '5 GB',
                ],
                'benchmark_scores' => [
                    'wer_librispeech' => 2.3,
                    'wer_common_voice' => 7.8,
                    'multilingual_support' => 99.0,
                ],
                'avg_inference_time_ms' => 800.00,
                'performance_tier' => 'standard',
                'model_url' => 'https://huggingface.co/openai/whisper-large-v3',
                'paper_url' => 'https://arxiv.org/abs/2212.04356',
                'demo_url' => 'https://huggingface.co/spaces/openai/whisper',
                'documentation_url' => 'https://huggingface.co/openai/whisper-large-v3',
                'supports_inference_api' => true,
                'supports_spaces' => true,
                'can_run_locally' => true,
                'compatible_cloud_providers' => ['runpod', 'vast-ai', 'google-colab', 'kaggle', 'lambda-labs'],
                'estimated_cost_per_hour' => 0.30,
                'rank_overall' => 4,
                'rank_in_category' => 1,
                'category' => 'Audio Processing',
                'is_featured' => true,
                'is_recommended' => true,
                'is_production_ready' => true,
                'difficulty_level' => 'beginner',
                'first_seen_at' => now()->subDays(150),
                'last_updated_at' => now()->subDays(15),
                'featured_at' => now()->subDays(120),
            ],

            // 🎥 Video Generation
            [
                'model_id' => 'ali-vilab/text-to-video-ms-1.7b',
                'model_name' => 'ModelScope Text-to-Video',
                'description' => 'โมเดลสร้างวิดีโอจากข้อความ ขนาด 1.7B parameters สร้างวิดีโอความยาว 2-4 วินาที ความละเอียด 256x256',
                'task' => 'text-to-video',
                'library' => 'diffusers',
                'tags' => ['text-to-video', 'video-generation', 'diffusion', 'modelscope'],
                'pipeline_tag' => ['text-to-video'],
                'author' => 'Alibaba DAMO Academy',
                'organization' => 'ali-vilab',
                'downloads' => 850000,
                'downloads_last_month' => 280000,
                'likes' => 9500,
                'trending_score' => 78,
                'model_size' => '6.8 GB',
                'model_size_bytes' => 7301447680,
                'supported_languages' => ['en'],
                'license' => 'cc-by-nc-4.0',
                'min_gpu_memory' => '16 GB',
                'recommended_gpu' => 'NVIDIA RTX 4090, A100',
                'hardware_requirements' => [
                    'min_vram' => '16 GB',
                    'recommended_vram' => '24 GB',
                    'min_ram' => '32 GB',
                    'storage' => '10 GB',
                ],
                'benchmark_scores' => [
                    'quality' => 7.5,
                    'temporal_consistency' => 8.2,
                    'prompt_adherence' => 7.8,
                ],
                'avg_inference_time_ms' => 25000.00,
                'performance_tier' => 'standard',
                'model_url' => 'https://huggingface.co/ali-vilab/text-to-video-ms-1.7b',
                'paper_url' => 'https://arxiv.org/abs/2308.06571',
                'demo_url' => 'https://huggingface.co/spaces/ali-vilab/modelscope-text-to-video',
                'documentation_url' => 'https://huggingface.co/ali-vilab/text-to-video-ms-1.7b',
                'supports_inference_api' => true,
                'supports_spaces' => true,
                'can_run_locally' => true,
                'compatible_cloud_providers' => ['runpod', 'vast-ai', 'lambda-labs'],
                'estimated_cost_per_hour' => 0.90,
                'rank_overall' => 8,
                'rank_in_category' => 1,
                'category' => 'Video Generation',
                'is_featured' => true,
                'is_recommended' => false,
                'is_production_ready' => true,
                'difficulty_level' => 'intermediate',
                'first_seen_at' => now()->subDays(180),
                'last_updated_at' => now()->subDays(20),
                'featured_at' => now()->subDays(150),
            ],

            // 💬 Chatbots & Conversational
            [
                'model_id' => 'HuggingFaceH4/zephyr-7b-beta',
                'model_name' => 'Zephyr 7B Beta',
                'description' => 'โมเดล chatbot ขนาด 7B ที่ fine-tuned จาก Mistral-7B ประสิทธิภาพเทียบเท่า ChatGPT 3.5 ใช้ทรัพยากรน้อย เหมาะสำหรับผู้เริ่มต้น',
                'task' => 'text-generation',
                'library' => 'transformers',
                'tags' => ['text-generation', 'conversational', 'chatbot', 'zephyr', 'instruct'],
                'pipeline_tag' => ['text-generation', 'conversational'],
                'author' => 'HuggingFace H4',
                'organization' => 'HuggingFaceH4',
                'downloads' => 3500000,
                'downloads_last_month' => 980000,
                'likes' => 16800,
                'trending_score' => 90,
                'model_size' => '14.4 GB',
                'model_size_bytes' => 15461882880,
                'supported_languages' => ['en'],
                'license' => 'mit',
                'min_gpu_memory' => '16 GB',
                'recommended_gpu' => 'NVIDIA RTX 4090, RTX 3090, T4',
                'hardware_requirements' => [
                    'min_vram' => '16 GB',
                    'recommended_vram' => '24 GB',
                    'min_ram' => '32 GB',
                    'storage' => '20 GB',
                ],
                'benchmark_scores' => [
                    'mmlu' => 61.4,
                    'mt_bench' => 7.34,
                    'alpaca_eval' => 90.6,
                ],
                'avg_inference_time_ms' => 450.00,
                'performance_tier' => 'standard',
                'model_url' => 'https://huggingface.co/HuggingFaceH4/zephyr-7b-beta',
                'paper_url' => 'https://arxiv.org/abs/2310.16944',
                'demo_url' => 'https://huggingface.co/spaces/HuggingFaceH4/zephyr-chat',
                'documentation_url' => 'https://huggingface.co/HuggingFaceH4/zephyr-7b-beta',
                'supports_inference_api' => true,
                'supports_spaces' => true,
                'can_run_locally' => true,
                'compatible_cloud_providers' => ['runpod', 'vast-ai', 'google-colab', 'kaggle', 'lightning-ai'],
                'estimated_cost_per_hour' => 0.40,
                'rank_overall' => 6,
                'rank_in_category' => 3,
                'category' => 'Language Model',
                'is_featured' => true,
                'is_recommended' => true,
                'is_production_ready' => true,
                'difficulty_level' => 'beginner',
                'first_seen_at' => now()->subDays(200),
                'last_updated_at' => now()->subDays(25),
                'featured_at' => now()->subDays(180),
            ],

            // 🖼️ Image Understanding & Vision
            [
                'model_id' => 'Salesforce/blip2-opt-2.7b',
                'model_name' => 'BLIP-2 OPT 2.7B',
                'description' => 'โมเดล Vision-Language ที่สามารถทำ Image Captioning, Visual Question Answering, และ Image-Text Retrieval ขนาดเล็กแต่แม่นยำ',
                'task' => 'image-to-text',
                'library' => 'transformers',
                'tags' => ['image-to-text', 'vision-language', 'blip', 'visual-question-answering', 'image-captioning'],
                'pipeline_tag' => ['image-to-text', 'visual-question-answering'],
                'author' => 'Salesforce',
                'organization' => 'Salesforce',
                'downloads' => 1200000,
                'downloads_last_month' => 420000,
                'likes' => 8900,
                'trending_score' => 75,
                'model_size' => '10.8 GB',
                'model_size_bytes' => 11594301440,
                'supported_languages' => ['en'],
                'license' => 'bsd-3-clause',
                'min_gpu_memory' => '12 GB',
                'recommended_gpu' => 'NVIDIA RTX 4080, RTX 3090, T4',
                'hardware_requirements' => [
                    'min_vram' => '12 GB',
                    'recommended_vram' => '16 GB',
                    'min_ram' => '24 GB',
                    'storage' => '15 GB',
                ],
                'benchmark_scores' => [
                    'coco_captioning_bleu4' => 40.4,
                    'vqa_accuracy' => 82.3,
                    'nocaps_cider' => 121.6,
                ],
                'avg_inference_time_ms' => 650.00,
                'performance_tier' => 'standard',
                'model_url' => 'https://huggingface.co/Salesforce/blip2-opt-2.7b',
                'paper_url' => 'https://arxiv.org/abs/2301.12597',
                'demo_url' => 'https://huggingface.co/spaces/Salesforce/BLIP2',
                'documentation_url' => 'https://huggingface.co/Salesforce/blip2-opt-2.7b',
                'supports_inference_api' => true,
                'supports_spaces' => true,
                'can_run_locally' => true,
                'compatible_cloud_providers' => ['runpod', 'vast-ai', 'google-colab', 'kaggle'],
                'estimated_cost_per_hour' => 0.35,
                'rank_overall' => 10,
                'rank_in_category' => 1,
                'category' => 'Vision-Language',
                'is_featured' => false,
                'is_recommended' => true,
                'is_production_ready' => true,
                'difficulty_level' => 'beginner',
                'first_seen_at' => now()->subDays(240),
                'last_updated_at' => now()->subDays(30),
                'featured_at' => null,
            ],

            // 🔊 Text-to-Speech
            [
                'model_id' => 'suno/bark',
                'model_name' => 'Bark',
                'description' => 'โมเดล Text-to-Audio ที่สามารถสร้างเสียงพูด เสียงดนตรี และเสียงอื่นๆ รองรับ multilingual และสามารถสร้างเสียงหัวเราะ, การร้องเพลง, เสียงพื้นหลัง',
                'task' => 'text-to-audio',
                'library' => 'transformers',
                'tags' => ['text-to-speech', 'text-to-audio', 'audio-generation', 'bark', 'multilingual'],
                'pipeline_tag' => ['text-to-audio', 'text-to-speech'],
                'author' => 'Suno AI',
                'organization' => 'suno',
                'downloads' => 920000,
                'downloads_last_month' => 310000,
                'likes' => 7600,
                'trending_score' => 72,
                'model_size' => '9.4 GB',
                'model_size_bytes' => 10092543385,
                'supported_languages' => ['en', 'zh', 'fr', 'de', 'multilingual'],
                'license' => 'cc-by-nc-4.0',
                'min_gpu_memory' => '12 GB',
                'recommended_gpu' => 'NVIDIA RTX 4080, RTX 3090',
                'hardware_requirements' => [
                    'min_vram' => '12 GB',
                    'recommended_vram' => '16 GB',
                    'min_ram' => '24 GB',
                    'storage' => '12 GB',
                ],
                'benchmark_scores' => [
                    'naturalness' => 8.5,
                    'intelligibility' => 9.1,
                    'expressiveness' => 9.3,
                ],
                'avg_inference_time_ms' => 3500.00,
                'performance_tier' => 'standard',
                'model_url' => 'https://huggingface.co/suno/bark',
                'paper_url' => null,
                'demo_url' => 'https://huggingface.co/spaces/suno/bark',
                'documentation_url' => 'https://github.com/suno-ai/bark',
                'supports_inference_api' => true,
                'supports_spaces' => true,
                'can_run_locally' => true,
                'compatible_cloud_providers' => ['runpod', 'vast-ai', 'google-colab', 'kaggle'],
                'estimated_cost_per_hour' => 0.38,
                'rank_overall' => 12,
                'rank_in_category' => 1,
                'category' => 'Audio Generation',
                'is_featured' => false,
                'is_recommended' => true,
                'is_production_ready' => true,
                'difficulty_level' => 'beginner',
                'first_seen_at' => now()->subDays(280),
                'last_updated_at' => now()->subDays(35),
                'featured_at' => null,
            ],

            // 🎯 Code Generation
            [
                'model_id' => 'bigcode/starcoder2-15b',
                'model_name' => 'StarCoder2 15B',
                'description' => 'โมเดลสร้างโค้ดที่ train บน 600+ ภาษาโปรแกรม รองรับ context length 16K tokens ประสิทธิภาพดีกว่า CodeLlama ในหลายงาน',
                'task' => 'text-generation',
                'library' => 'transformers',
                'tags' => ['code-generation', 'text-generation', 'starcoder', 'programming', 'multilingual-code'],
                'pipeline_tag' => ['text-generation'],
                'author' => 'BigCode',
                'organization' => 'bigcode',
                'downloads' => 780000,
                'downloads_last_month' => 260000,
                'likes' => 6800,
                'trending_score' => 70,
                'model_size' => '30 GB',
                'model_size_bytes' => 32212254720,
                'supported_languages' => ['code', 'multilingual'],
                'license' => 'bigcode-openrail-m',
                'min_gpu_memory' => '32 GB',
                'recommended_gpu' => 'NVIDIA A100, RTX 4090',
                'hardware_requirements' => [
                    'min_vram' => '32 GB',
                    'recommended_vram' => '40 GB',
                    'min_ram' => '64 GB',
                    'storage' => '35 GB',
                ],
                'benchmark_scores' => [
                    'humaneval' => 46.2,
                    'mbpp' => 61.6,
                    'ds1000' => 43.8,
                ],
                'avg_inference_time_ms' => 850.00,
                'performance_tier' => 'standard',
                'model_url' => 'https://huggingface.co/bigcode/starcoder2-15b',
                'paper_url' => 'https://arxiv.org/abs/2402.19173',
                'demo_url' => 'https://huggingface.co/spaces/bigcode/starcoder2',
                'documentation_url' => 'https://huggingface.co/bigcode/starcoder2-15b',
                'supports_inference_api' => true,
                'supports_spaces' => true,
                'can_run_locally' => true,
                'compatible_cloud_providers' => ['runpod', 'vast-ai', 'lambda-labs'],
                'estimated_cost_per_hour' => 1.20,
                'rank_overall' => 14,
                'rank_in_category' => 1,
                'category' => 'Code Generation',
                'is_featured' => false,
                'is_recommended' => true,
                'is_production_ready' => true,
                'difficulty_level' => 'intermediate',
                'first_seen_at' => now()->subDays(90),
                'last_updated_at' => now()->subDays(12),
                'featured_at' => null,
            ],

            // 🌐 Translation
            [
                'model_id' => 'facebook/nllb-200-3.3B',
                'model_name' => 'NLLB-200 3.3B',
                'description' => 'โมเดลแปลภาษาที่รองรับ 200 ภาษา รวมภาษาไทย แปลได้แม่นยำและรวดเร็ว เหมาะสำหรับการแปลเอกสารและ web content',
                'task' => 'translation',
                'library' => 'transformers',
                'tags' => ['translation', 'nllb', 'multilingual', 'low-resource-languages'],
                'pipeline_tag' => ['translation'],
                'author' => 'Meta AI',
                'organization' => 'facebook',
                'downloads' => 1500000,
                'downloads_last_month' => 520000,
                'likes' => 10200,
                'trending_score' => 80,
                'model_size' => '13.2 GB',
                'model_size_bytes' => 14172258304,
                'supported_languages' => ['multilingual', 'th', 'en'],
                'license' => 'cc-by-nc-4.0',
                'min_gpu_memory' => '14 GB',
                'recommended_gpu' => 'NVIDIA RTX 4090, RTX 3090, T4',
                'hardware_requirements' => [
                    'min_vram' => '14 GB',
                    'recommended_vram' => '16 GB',
                    'min_ram' => '32 GB',
                    'storage' => '15 GB',
                ],
                'benchmark_scores' => [
                    'flores_bleu' => 32.8,
                    'chrF' => 58.4,
                ],
                'avg_inference_time_ms' => 550.00,
                'performance_tier' => 'standard',
                'model_url' => 'https://huggingface.co/facebook/nllb-200-3.3B',
                'paper_url' => 'https://arxiv.org/abs/2207.04672',
                'demo_url' => 'https://huggingface.co/spaces/facebook/nllb-translation',
                'documentation_url' => 'https://huggingface.co/facebook/nllb-200-3.3B',
                'supports_inference_api' => true,
                'supports_spaces' => true,
                'can_run_locally' => true,
                'compatible_cloud_providers' => ['runpod', 'vast-ai', 'google-colab', 'kaggle', 'lightning-ai'],
                'estimated_cost_per_hour' => 0.42,
                'rank_overall' => 11,
                'rank_in_category' => 1,
                'category' => 'Translation',
                'is_featured' => false,
                'is_recommended' => true,
                'is_production_ready' => true,
                'difficulty_level' => 'beginner',
                'first_seen_at' => now()->subDays(320),
                'last_updated_at' => now()->subDays(40),
                'featured_at' => null,
            ],

            // 📝 Text Embeddings
            [
                'model_id' => 'BAAI/bge-large-en-v1.5',
                'model_name' => 'BGE Large EN v1.5',
                'description' => 'โมเดล text embeddings ที่มีประสิทธิภาพสูง เหมาะสำหรับ semantic search, RAG systems, และ document retrieval',
                'task' => 'feature-extraction',
                'library' => 'sentence-transformers',
                'tags' => ['sentence-transformers', 'feature-extraction', 'embeddings', 'semantic-search', 'rag'],
                'pipeline_tag' => ['feature-extraction'],
                'author' => 'Beijing Academy of AI',
                'organization' => 'BAAI',
                'downloads' => 2800000,
                'downloads_last_month' => 890000,
                'likes' => 13500,
                'trending_score' => 84,
                'model_size' => '1.3 GB',
                'model_size_bytes' => 1395864371,
                'supported_languages' => ['en'],
                'license' => 'mit',
                'min_gpu_memory' => '4 GB',
                'recommended_gpu' => 'NVIDIA T4, RTX 3060',
                'hardware_requirements' => [
                    'min_vram' => '4 GB',
                    'recommended_vram' => '8 GB',
                    'min_ram' => '8 GB',
                    'storage' => '2 GB',
                ],
                'benchmark_scores' => [
                    'mteb_avg' => 63.98,
                    'ndcg@10' => 59.46,
                ],
                'avg_inference_time_ms' => 50.00,
                'performance_tier' => 'efficient',
                'model_url' => 'https://huggingface.co/BAAI/bge-large-en-v1.5',
                'paper_url' => 'https://arxiv.org/abs/2309.07597',
                'demo_url' => null,
                'documentation_url' => 'https://github.com/FlagOpen/FlagEmbedding',
                'supports_inference_api' => true,
                'supports_spaces' => true,
                'can_run_locally' => true,
                'compatible_cloud_providers' => ['runpod', 'vast-ai', 'google-colab', 'kaggle', 'lightning-ai'],
                'estimated_cost_per_hour' => 0.15,
                'rank_overall' => 7,
                'rank_in_category' => 1,
                'category' => 'Embeddings',
                'is_featured' => true,
                'is_recommended' => true,
                'is_production_ready' => true,
                'difficulty_level' => 'beginner',
                'first_seen_at' => now()->subDays(180),
                'last_updated_at' => now()->subDays(18),
                'featured_at' => now()->subDays(150),
            ],

            // 🎭 Multi-modal Models
            [
                'model_id' => 'liuhaotian/llava-v1.6-mistral-7b',
                'model_name' => 'LLaVA 1.6 Mistral 7B',
                'description' => 'โมเดล Vision-Language ที่สามารถรับทั้งรูปภาพและข้อความ ตอบคำถามเกี่ยวกับรูปภาพ และอธิบายเนื้อหาในภาพได้แม่นยำ',
                'task' => 'image-text-to-text',
                'library' => 'transformers',
                'tags' => ['image-text-to-text', 'vision-language', 'llava', 'multimodal', 'visual-question-answering'],
                'pipeline_tag' => ['image-text-to-text'],
                'author' => 'Haotian Liu',
                'organization' => 'liuhaotian',
                'downloads' => 650000,
                'downloads_last_month' => 220000,
                'likes' => 5900,
                'trending_score' => 68,
                'model_size' => '14.5 GB',
                'model_size_bytes' => 15569133568,
                'supported_languages' => ['en'],
                'license' => 'apache-2.0',
                'min_gpu_memory' => '16 GB',
                'recommended_gpu' => 'NVIDIA RTX 4090, RTX 3090',
                'hardware_requirements' => [
                    'min_vram' => '16 GB',
                    'recommended_vram' => '24 GB',
                    'min_ram' => '32 GB',
                    'storage' => '18 GB',
                ],
                'benchmark_scores' => [
                    'vqa_v2' => 80.9,
                    'gqa' => 64.2,
                    'textvqa' => 58.2,
                ],
                'avg_inference_time_ms' => 1200.00,
                'performance_tier' => 'standard',
                'model_url' => 'https://huggingface.co/liuhaotian/llava-v1.6-mistral-7b',
                'paper_url' => 'https://arxiv.org/abs/2310.03744',
                'demo_url' => 'https://llava.hliu.cc',
                'documentation_url' => 'https://github.com/haotian-liu/LLaVA',
                'supports_inference_api' => true,
                'supports_spaces' => true,
                'can_run_locally' => true,
                'compatible_cloud_providers' => ['runpod', 'vast-ai', 'lambda-labs'],
                'estimated_cost_per_hour' => 0.55,
                'rank_overall' => 13,
                'rank_in_category' => 2,
                'category' => 'Vision-Language',
                'is_featured' => false,
                'is_recommended' => false,
                'is_production_ready' => true,
                'difficulty_level' => 'intermediate',
                'first_seen_at' => now()->subDays(100),
                'last_updated_at' => now()->subDays(8),
                'featured_at' => null,
            ],
        ];

        // สร้างข้อมูล trending models
        foreach ($models as $modelData) {
            HuggingFaceTrendingModel::create($modelData);
            $this->command->info("  ✅ {$modelData['model_name']} ({$modelData['category']})");
        }

        $this->command->info('✅ Seed Trending Models สำเร็จ! สร้างทั้งหมด ' . count($models) . ' models');
    }
}
