<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MlmGlobalSettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            // General Settings
            [
                'key' => 'mlm_enabled',
                'value' => '1',
                'type' => 'boolean',
                'input_type' => 'toggle',
                'group' => 'general',
                'description' => 'Enable/Disable MLM System',
                'description_th' => 'เปิด/ปิดระบบ MLM',
                'sort_order' => 1,
            ],
            [
                'key' => 'mlm_system_name',
                'value' => 'Thai Prompt MLM',
                'type' => 'string',
                'input_type' => 'text',
                'group' => 'general',
                'description' => 'MLM System Name',
                'description_th' => 'ชื่อระบบ MLM',
                'placeholder' => 'ระบุชื่อระบบ MLM',
                'sort_order' => 2,
            ],
            [
                'key' => 'default_currency',
                'value' => 'THB',
                'type' => 'string',
                'input_type' => 'select',
                'allowed_values' => json_encode(['THB', 'USD', 'EUR', 'GBP', 'JPY']),
                'group' => 'general',
                'description' => 'Default Currency',
                'description_th' => 'สกุลเงินเริ่มต้น',
                'sort_order' => 3,
            ],

            // PV System
            [
                'key' => 'global_pv_rate',
                'value' => '1.00',
                'type' => 'decimal',
                'input_type' => 'number',
                'group' => 'pv',
                'description' => 'Global PV Rate (1 THB = X PV)',
                'description_th' => 'อัตราแปลง PV ทั่วไป (1 บาท = X PV)',
                'placeholder' => '1.00',
                'unit' => 'PV',
                'sort_order' => 10,
            ],
            [
                'key' => 'commission_per_pv',
                'value' => '1.00',
                'type' => 'decimal',
                'input_type' => 'number',
                'group' => 'pv',
                'description' => 'Commission per 1 PV (THB)',
                'description_th' => 'ค่าคอมมิชชันต่อ 1 PV (บาท)',
                'placeholder' => '1.00',
                'unit' => 'บาท',
                'sort_order' => 11,
            ],

            // Unilevel Settings
            [
                'key' => 'unilevel_max_depth',
                'value' => '10',
                'type' => 'integer',
                'input_type' => 'number',
                'group' => 'unilevel',
                'description' => 'Maximum Unilevel Depth',
                'description_th' => 'ระดับ Unilevel สูงสุด',
                'placeholder' => '10',
                'unit' => 'ชั้น',
                'sort_order' => 20,
            ],
            [
                'key' => 'unilevel_max_width',
                'value' => null,
                'type' => 'integer',
                'input_type' => 'number',
                'group' => 'unilevel',
                'description' => 'Maximum Direct Referrals per Member (null = unlimited)',
                'description_th' => 'จำนวนลูกตรงสูงสุดต่อสมาชิก (null = ไม่จำกัด)',
                'placeholder' => 'ไม่จำกัด',
                'unit' => 'คน',
                'sort_order' => 21,
            ],
            [
                'key' => 'unilevel_auto_spillover',
                'value' => '1',
                'type' => 'boolean',
                'input_type' => 'toggle',
                'group' => 'unilevel',
                'description' => 'Auto spillover when width limit reached (fill level by level)',
                'description_th' => 'ล้นอัตโนมัติเมื่อเกินจำนวนลูกตรง (เติมเต็มชั้นก่อน)',
                'sort_order' => 22,
            ],
            [
                'key' => 'unilevel_levels',
                'value' => json_encode([
                    ['level' => 1, 'percentage' => 10],
                    ['level' => 2, 'percentage' => 5],
                    ['level' => 3, 'percentage' => 3],
                    ['level' => 4, 'percentage' => 2],
                    ['level' => 5, 'percentage' => 1],
                    ['level' => 6, 'percentage' => 1],
                    ['level' => 7, 'percentage' => 1],
                    ['level' => 8, 'percentage' => 1],
                    ['level' => 9, 'percentage' => 1],
                    ['level' => 10, 'percentage' => 1],
                ]),
                'type' => 'json',
                'input_type' => 'unilevel_editor',
                'group' => 'unilevel',
                'description' => 'Unilevel Commission Percentages by Level',
                'description_th' => 'เปอร์เซ็นต์คอมมิชชัน Unilevel แต่ละระดับ',
                'sort_order' => 23,
            ],
            [
                'key' => 'unilevel_compression_enabled',
                'value' => '1',
                'type' => 'boolean',
                'input_type' => 'toggle',
                'group' => 'unilevel',
                'description' => 'Enable Unilevel Compression (Skip inactive members)',
                'description_th' => 'เปิดใช้ Compression (ข้ามคนไม่ active)',
                'sort_order' => 24,
            ],
            [
                'key' => 'unilevel_max_commission_per_level',
                'value' => null,
                'type' => 'decimal',
                'input_type' => 'number',
                'group' => 'unilevel',
                'description' => 'Maximum Commission per Level (null = unlimited)',
                'description_th' => 'คอมมิชชันสูงสุดต่อระดับ (null = ไม่จำกัด)',
                'placeholder' => 'ไม่จำกัด',
                'unit' => 'บาท',
                'sort_order' => 25,
            ],

            // Binary Settings
            [
                'key' => 'binary_pair_commission',
                'value' => '100.00',
                'type' => 'decimal',
                'input_type' => 'number',
                'group' => 'binary',
                'description' => 'Commission per Pair (THB)',
                'description_th' => 'ค่าคอมมิชชันต่อคู่ (บาท)',
                'placeholder' => '100.00',
                'unit' => 'บาท',
                'sort_order' => 30,
            ],
            [
                'key' => 'binary_match_percentage',
                'value' => '50.00',
                'type' => 'decimal',
                'input_type' => 'number',
                'group' => 'binary',
                'description' => 'Binary Match Percentage (%)',
                'description_th' => 'เปอร์เซ็นต์การจับคู่ Binary (%)',
                'placeholder' => '50.00',
                'unit' => '%',
                'sort_order' => 31,
            ],
            [
                'key' => 'binary_max_pairs_per_day',
                'value' => null,
                'type' => 'integer',
                'input_type' => 'number',
                'group' => 'binary',
                'description' => 'Maximum Pairs per Day (null = unlimited)',
                'description_th' => 'จำนวนคู่สูงสุดต่อวัน (null = ไม่จำกัด)',
                'placeholder' => 'ไม่จำกัด',
                'unit' => 'คู่',
                'sort_order' => 32,
            ],
            [
                'key' => 'binary_max_commission_per_day',
                'value' => null,
                'type' => 'decimal',
                'input_type' => 'number',
                'group' => 'binary',
                'description' => 'Maximum Commission per Day (THB, null = unlimited)',
                'description_th' => 'คอมมิชชันสูงสุดต่อวัน (บาท, null = ไม่จำกัด)',
                'placeholder' => 'ไม่จำกัด',
                'unit' => 'บาท/วัน',
                'sort_order' => 33,
            ],
            [
                'key' => 'binary_spillover_enabled',
                'value' => '1',
                'type' => 'boolean',
                'input_type' => 'toggle',
                'group' => 'binary',
                'description' => 'Enable Binary Spillover',
                'description_th' => 'เปิดใช้ Binary Spillover',
                'sort_order' => 34,
            ],
            [
                'key' => 'binary_pairing_type',
                'value' => '1:1',
                'type' => 'string',
                'input_type' => 'select',
                'allowed_values' => json_encode(['1:1', '2:1']),
                'group' => 'binary',
                'description' => 'Binary Pairing Type (1:1 or 2:1)',
                'description_th' => 'ประเภทการจับคู่ Binary (1:1 หรือ 2:1)',
                'sort_order' => 35,
            ],
            [
                'key' => 'binary_default_left_ratio',
                'value' => '50',
                'type' => 'integer',
                'input_type' => 'number',
                'group' => 'binary',
                'description' => 'Default Left Leg Ratio for Simulation (%)',
                'description_th' => 'สัดส่วนขาซ้ายเริ่มต้นสำหรับการจำลอง (%)',
                'placeholder' => '50',
                'unit' => '%',
                'sort_order' => 36,
            ],
            [
                'key' => 'binary_enabled',
                'value' => '1',
                'type' => 'boolean',
                'input_type' => 'toggle',
                'group' => 'binary',
                'description' => 'Enable Binary Commission System',
                'description_th' => 'เปิดใช้ระบบคอมมิชชัน Binary',
                'sort_order' => 37,
            ],
            [
                'key' => 'unilevel_enabled',
                'value' => '1',
                'type' => 'boolean',
                'input_type' => 'toggle',
                'group' => 'unilevel',
                'description' => 'Enable Unilevel Commission System',
                'description_th' => 'เปิดใช้ระบบคอมมิชชัน Unilevel',
                'sort_order' => 24,
            ],

            // Flush Settings
            [
                'key' => 'binary_flush_mode',
                'value' => 'percentage',
                'type' => 'string',
                'input_type' => 'select',
                'allowed_values' => json_encode(['percentage', 'full', 'none']),
                'group' => 'flush',
                'description' => 'Flush Mode (percentage, full, none)',
                'description_th' => 'โหมดการล้าง PV',
                'sort_order' => 40,
            ],
            [
                'key' => 'binary_flush_percentage',
                'value' => '100.00',
                'type' => 'decimal',
                'input_type' => 'number',
                'group' => 'flush',
                'description' => 'Flush Percentage (%)',
                'description_th' => 'เปอร์เซ็นต์การล้าง PV (%)',
                'placeholder' => '100.00',
                'unit' => '%',
                'sort_order' => 41,
            ],
            [
                'key' => 'binary_carry_forward_enabled',
                'value' => '0',
                'type' => 'boolean',
                'input_type' => 'toggle',
                'group' => 'flush',
                'description' => 'Enable Carry Forward PV',
                'description_th' => 'เปิดใช้การยกยอด PV',
                'sort_order' => 42,
            ],
            [
                'key' => 'binary_carry_forward_days',
                'value' => '30',
                'type' => 'integer',
                'input_type' => 'number',
                'group' => 'flush',
                'description' => 'Carry Forward Days',
                'description_th' => 'จำนวนวันที่ยกยอด',
                'placeholder' => '30',
                'unit' => 'วัน',
                'sort_order' => 43,
            ],

            // Auto Placement
            [
                'key' => 'auto_placement_enabled',
                'value' => '1',
                'type' => 'boolean',
                'input_type' => 'toggle',
                'group' => 'placement',
                'description' => 'Enable Auto Placement',
                'description_th' => 'เปิดใช้การจัดวางอัตโนมัติ',
                'sort_order' => 50,
            ],
            [
                'key' => 'auto_placement_strategy',
                'value' => 'fill_level',
                'type' => 'string',
                'input_type' => 'select',
                'allowed_values' => json_encode(['manual', 'left_first', 'right_first', 'fill_level', 'weak_leg', 'strong_leg', 'balanced']),
                'group' => 'placement',
                'description' => 'Auto Placement Strategy',
                'description_th' => 'กลยุทธ์การจัดวางอัตโนมัติ',
                'sort_order' => 51,
            ],

            // Binary Tree Structure Limits (ความลึกและความกว้างของ Binary Tree)
            [
                'key' => 'binary_max_depth',
                'value' => '10',
                'type' => 'integer',
                'input_type' => 'number',
                'group' => 'placement',
                'description' => 'Maximum Binary Tree Depth (null = unlimited)',
                'description_th' => 'ความลึกสูงสุดของ Binary Tree (null = ไม่จำกัด)',
                'placeholder' => '10',
                'unit' => 'ชั้น',
                'sort_order' => 52,
            ],
            [
                'key' => 'binary_max_width',
                'value' => '2',
                'type' => 'integer',
                'input_type' => 'number',
                'group' => 'placement',
                'description' => 'Maximum Children per Node (2 = Binary, 3 = Ternary)',
                'description_th' => 'จำนวนลูกสูงสุดต่อ node (2 = Binary, 3 = Ternary)',
                'placeholder' => '2',
                'unit' => 'คน',
                'sort_order' => 53,
            ],
            [
                'key' => 'binary_auto_place_on_register',
                'value' => '1',
                'type' => 'boolean',
                'input_type' => 'toggle',
                'group' => 'placement',
                'description' => 'Auto place in Binary Tree when member registers',
                'description_th' => 'จัดวางใน Binary Tree อัตโนมัติเมื่อสมัครสมาชิก',
                'sort_order' => 54,
            ],

            // Roll-up/Compression
            [
                'key' => 'rollup_enabled',
                'value' => '1',
                'type' => 'boolean',
                'input_type' => 'toggle',
                'group' => 'rollup',
                'description' => 'Enable Roll-up (Commission compression for inactive members)',
                'description_th' => 'เปิดใช้ Roll-up (ปันผลข้ามคนที่ไม่รักษายอด)',
                'sort_order' => 60,
            ],
            [
                'key' => 'rollup_prevent_duplicate',
                'value' => '1',
                'type' => 'boolean',
                'input_type' => 'toggle',
                'group' => 'rollup',
                'description' => 'Prevent Duplicate Roll-up Commission',
                'description_th' => 'ป้องกันการได้ปันผล Roll-up ซ้ำ',
                'sort_order' => 61,
            ],
            [
                'key' => 'rollup_max_levels',
                'value' => '10',
                'type' => 'integer',
                'input_type' => 'number',
                'group' => 'rollup',
                'description' => 'Maximum Levels to Roll-up',
                'description_th' => 'จำนวนระดับสูงสุดที่จะ Roll-up',
                'placeholder' => '10',
                'unit' => 'ชั้น',
                'sort_order' => 62,
            ],

            // Volume Retention (รักษายอด)
            [
                'key' => 'volume_retention_enabled',
                'value' => '1',
                'type' => 'boolean',
                'input_type' => 'toggle',
                'group' => 'retention',
                'description' => 'Enable Volume Retention Requirement',
                'description_th' => 'เปิดใช้ระบบรักษายอด',
                'sort_order' => 70,
            ],
            [
                'key' => 'volume_retention_monthly_pv',
                'value' => '100',
                'type' => 'decimal',
                'input_type' => 'number',
                'group' => 'retention',
                'description' => 'Monthly PV Requirement',
                'description_th' => 'PV ที่ต้องรักษาต่อเดือน',
                'placeholder' => '100',
                'unit' => 'PV/เดือน',
                'sort_order' => 71,
            ],
            [
                'key' => 'volume_retention_grace_days',
                'value' => '7',
                'type' => 'integer',
                'input_type' => 'number',
                'group' => 'retention',
                'description' => 'Grace Period Days (Yellow warning)',
                'description_th' => 'จำนวนวันผ่อนผัน (แจ้งเตือนเหลือง)',
                'placeholder' => '7',
                'unit' => 'วัน',
                'sort_order' => 72,
            ],

            // Overpay Protection
            [
                'key' => 'overpay_protection_enabled',
                'value' => '1',
                'type' => 'boolean',
                'input_type' => 'toggle',
                'group' => 'commission',
                'description' => 'Enable Overpay Protection',
                'description_th' => 'เปิดใช้ระบบป้องกัน Overpay',
                'sort_order' => 80,
            ],
            [
                'key' => 'max_commission_percentage',
                'value' => '50.00',
                'type' => 'decimal',
                'input_type' => 'number',
                'group' => 'commission',
                'description' => 'Maximum Total Commission Percentage (%)',
                'description_th' => 'เปอร์เซ็นต์คอมมิชชันรวมสูงสุด (%)',
                'placeholder' => '50.00',
                'unit' => '%',
                'sort_order' => 81,
            ],

            // Genealogy System (ผังสายเลือด - ค่าแนะนำตรง)
            // หมายเหตุ: ค่าแนะนำตรงเป็นคนละส่วนกับ PV Commission ของ Unilevel/Binary
            // จ่ายให้ผู้แนะนำตรงจริงๆ (original_sponsor) ไม่มี spillover
            [
                'key' => 'genealogy_enabled',
                'value' => '1',
                'type' => 'boolean',
                'input_type' => 'toggle',
                'group' => 'referral',
                'description' => 'Enable Genealogy Commission System (Direct Referral)',
                'description_th' => 'เปิดใช้ระบบคอมมิชชั่นผังสายเลือด (ค่าแนะนำตรง)',
                'sort_order' => 89,
            ],
            [
                'key' => 'direct_referral_bonus_enabled',
                'value' => '1',
                'type' => 'boolean',
                'input_type' => 'toggle',
                'group' => 'referral',
                'description' => 'Enable Direct Referral Bonus (One-time payment to original sponsor)',
                'description_th' => 'เปิดใช้ค่าแนะนำตรง (จ่ายครั้งเดียวให้ผู้แนะนำจริง)',
                'sort_order' => 90,
            ],
            [
                'key' => 'direct_referral_bonus_type',
                'value' => 'fixed',
                'type' => 'string',
                'input_type' => 'select',
                'allowed_values' => json_encode(['fixed', 'percentage']),
                'group' => 'referral',
                'description' => 'Referral Bonus Type (fixed amount or percentage of order)',
                'description_th' => 'ประเภทค่าแนะนำ (จำนวนคงที่ หรือ เปอร์เซ็นต์จากยอดสั่งซื้อ)',
                'sort_order' => 91,
            ],
            [
                'key' => 'direct_referral_bonus_amount',
                'value' => '100.00',
                'type' => 'decimal',
                'input_type' => 'number',
                'group' => 'referral',
                'description' => 'Fixed Referral Bonus Amount (THB)',
                'description_th' => 'จำนวนค่าแนะนำตรงคงที่ (บาท)',
                'placeholder' => '100.00',
                'unit' => 'บาท',
                'sort_order' => 92,
            ],
            [
                'key' => 'direct_referral_bonus_percentage',
                'value' => '5.00',
                'type' => 'decimal',
                'input_type' => 'number',
                'group' => 'referral',
                'description' => 'Referral Bonus Percentage (% of order total)',
                'description_th' => 'เปอร์เซ็นต์ค่าแนะนำตรง (% ของยอดสั่งซื้อ)',
                'placeholder' => '5.00',
                'unit' => '%',
                'sort_order' => 93,
            ],
            [
                'key' => 'direct_referral_bonus_min_order',
                'value' => '0',
                'type' => 'decimal',
                'input_type' => 'number',
                'group' => 'referral',
                'description' => 'Minimum Order Amount to Qualify for Referral Bonus',
                'description_th' => 'ยอดสั่งซื้อขั้นต่ำที่จะได้รับค่าแนะนำ',
                'placeholder' => '0',
                'unit' => 'บาท',
                'sort_order' => 94,
            ],
            [
                'key' => 'direct_referral_bonus_max_per_order',
                'value' => null,
                'type' => 'decimal',
                'input_type' => 'number',
                'group' => 'referral',
                'description' => 'Maximum Referral Bonus per Order (null = unlimited)',
                'description_th' => 'ค่าแนะนำสูงสุดต่อออเดอร์ (null = ไม่จำกัด)',
                'placeholder' => 'ไม่จำกัด',
                'unit' => 'บาท',
                'sort_order' => 95,
            ],
            [
                'key' => 'direct_referral_bonus_first_order_only',
                'value' => '0',
                'type' => 'boolean',
                'input_type' => 'toggle',
                'group' => 'referral',
                'description' => 'Referral Bonus only for first order (one-time)',
                'description_th' => 'จ่ายค่าแนะนำเฉพาะออเดอร์แรก (ครั้งเดียว)',
                'sort_order' => 96,
            ],

            // ========================================
            // Pool Bonus (All Sale Bonus) Settings
            // ========================================
            [
                'key' => 'pool_bonus_enabled',
                'value' => '1',
                'type' => 'boolean',
                'input_type' => 'toggle',
                'group' => 'pool_bonus',
                'description' => 'Enable Pool Bonus (All Sale Bonus)',
                'description_th' => 'เปิดใช้ Pool Bonus (โบนัสจากยอดขายรวม)',
                'sort_order' => 100,
            ],
            [
                'key' => 'pool_bonus_percentage',
                'value' => '5.00',
                'type' => 'decimal',
                'input_type' => 'number',
                'group' => 'pool_bonus',
                'description' => 'Percentage of total sales to pool (%)',
                'description_th' => 'เปอร์เซ็นต์ของยอดขายที่หักเข้า Pool (%)',
                'placeholder' => '5.00',
                'unit' => '%',
                'sort_order' => 101,
            ],
            [
                'key' => 'pool_bonus_period_type',
                'value' => 'weekly',
                'type' => 'string',
                'input_type' => 'select',
                'allowed_values' => json_encode(['daily', 'weekly', 'monthly']),
                'group' => 'pool_bonus',
                'description' => 'Pool Bonus calculation period',
                'description_th' => 'รอบการคำนวณ Pool Bonus',
                'sort_order' => 102,
            ],
            [
                'key' => 'pool_bonus_share_mode',
                'value' => 'rank_based',
                'type' => 'string',
                'input_type' => 'select',
                'allowed_values' => json_encode(['equal', 'rank_based', 'pv_based']),
                'group' => 'pool_bonus',
                'description' => 'How to distribute shares (equal = everyone same, rank_based = by rank, pv_based = by PV)',
                'description_th' => 'วิธีการแบ่ง shares (equal = เท่ากัน, rank_based = ตาม rank, pv_based = ตาม PV)',
                'sort_order' => 103,
            ],
            [
                'key' => 'pool_bonus_base_shares',
                'value' => '1',
                'type' => 'integer',
                'input_type' => 'number',
                'group' => 'pool_bonus',
                'description' => 'Base shares for each member',
                'description_th' => 'จำนวน shares พื้นฐานต่อคน',
                'placeholder' => '1',
                'unit' => 'shares',
                'sort_order' => 104,
            ],
            [
                'key' => 'pool_bonus_min_personal_pv',
                'value' => '0',
                'type' => 'decimal',
                'input_type' => 'number',
                'group' => 'pool_bonus',
                'description' => 'Minimum personal PV to qualify for Pool Bonus',
                'description_th' => 'PV ส่วนตัวขั้นต่ำเพื่อรับ Pool Bonus',
                'placeholder' => '0',
                'unit' => 'PV',
                'sort_order' => 105,
            ],
            [
                'key' => 'pool_bonus_min_team_pv',
                'value' => '0',
                'type' => 'decimal',
                'input_type' => 'number',
                'group' => 'pool_bonus',
                'description' => 'Minimum team PV to qualify for Pool Bonus',
                'description_th' => 'PV ทีมขั้นต่ำเพื่อรับ Pool Bonus',
                'placeholder' => '0',
                'unit' => 'PV',
                'sort_order' => 106,
            ],
            [
                'key' => 'pool_bonus_min_rank_level',
                'value' => '0',
                'type' => 'integer',
                'input_type' => 'number',
                'group' => 'pool_bonus',
                'description' => 'Minimum rank level to qualify (0 = no requirement)',
                'description_th' => 'Rank ขั้นต่ำที่ต้องมี (0 = ไม่กำหนด)',
                'placeholder' => '0',
                'unit' => 'level',
                'sort_order' => 107,
            ],
            [
                'key' => 'pool_bonus_require_active',
                'value' => '1',
                'type' => 'boolean',
                'input_type' => 'toggle',
                'group' => 'pool_bonus',
                'description' => 'Require member to be active (qualified)',
                'description_th' => 'ต้องเป็นสมาชิก active (qualified) เท่านั้น',
                'sort_order' => 108,
            ],
            [
                'key' => 'pool_bonus_pv_per_share',
                'value' => '100',
                'type' => 'decimal',
                'input_type' => 'number',
                'group' => 'pool_bonus',
                'description' => 'PV required for 1 additional share (for pv_based mode)',
                'description_th' => 'PV ที่ต้องทำเพื่อได้ 1 share เพิ่ม (สำหรับโหมด pv_based)',
                'placeholder' => '100',
                'unit' => 'PV',
                'sort_order' => 109,
            ],
            [
                'key' => 'pool_bonus_rank_shares',
                'value' => json_encode([
                    1 => 1,  // Rank level 1 = 1 share
                    2 => 2,  // Rank level 2 = 2 shares
                    3 => 3,  // Rank level 3 = 3 shares
                    4 => 5,  // Rank level 4 = 5 shares
                    5 => 8,  // Rank level 5 = 8 shares
                    6 => 13, // Rank level 6 = 13 shares
                ]),
                'type' => 'json',
                'input_type' => 'json_editor',
                'group' => 'pool_bonus',
                'description' => 'Shares per rank level (JSON: {rank_id: shares})',
                'description_th' => 'จำนวน shares ตาม rank (JSON: {rank_id: shares})',
                'sort_order' => 110,
            ],
            [
                'key' => 'pool_bonus_auto_distribute',
                'value' => '0',
                'type' => 'boolean',
                'input_type' => 'toggle',
                'group' => 'pool_bonus',
                'description' => 'Auto calculate and distribute at end of period',
                'description_th' => 'คำนวณและกระจายอัตโนมัติเมื่อสิ้นสุดรอบ',
                'sort_order' => 111,
            ],
            [
                'key' => 'pool_bonus_auto_pay',
                'value' => '0',
                'type' => 'boolean',
                'input_type' => 'toggle',
                'group' => 'pool_bonus',
                'description' => 'Auto pay after distribution (skip approval)',
                'description_th' => 'จ่ายอัตโนมัติหลังกระจาย (ข้ามการอนุมัติ)',
                'sort_order' => 112,
            ],

            // ========================================
            // Roll-up Distribution Settings
            // ========================================
            [
                'key' => 'rollup_distribution_mode',
                'value' => 'distributed',
                'type' => 'string',
                'input_type' => 'select',
                'allowed_values' => json_encode(['single', 'distributed', 'proportional']),
                'group' => 'rollup',
                'description' => 'Roll-up distribution mode (single = to one upline, distributed = spread to multiple, proportional = by level)',
                'description_th' => 'โหมดการกระจาย Roll-up (single = ไปคนเดียว, distributed = กระจายหลายคน, proportional = ตามสัดส่วน level)',
                'sort_order' => 63,
            ],
            [
                'key' => 'rollup_max_per_member',
                'value' => '3',
                'type' => 'integer',
                'input_type' => 'number',
                'group' => 'rollup',
                'description' => 'Maximum rollup commissions per member per transaction',
                'description_th' => 'จำนวน rollup สูงสุดที่คนเดียวจะได้รับต่อ transaction',
                'placeholder' => '3',
                'unit' => 'ครั้ง',
                'sort_order' => 64,
            ],
            [
                'key' => 'rollup_to_pool_enabled',
                'value' => '1',
                'type' => 'boolean',
                'input_type' => 'toggle',
                'group' => 'rollup',
                'description' => 'Send excess rollup to Pool Bonus instead of admin',
                'description_th' => 'ส่ง rollup ที่เกินไปยัง Pool Bonus แทนที่จะไป admin',
                'sort_order' => 65,
            ],
        ];

        // ⚠️ Smart Seeding: ใช้ updateOrCreate แทน truncate
        // เพื่อรักษาค่าที่ผู้ใช้ตั้งค่าไว้ ไม่ให้ถูกรีเซ็ตเมื่อ deploy
        // - ค่าที่มีอยู่แล้ว: จะไม่ถูกเปลี่ยนแปลง (preserve user customizations)
        // - ค่าใหม่ที่ยังไม่มี: จะถูกเพิ่มเข้าไป (add new settings)

        $insertedCount = 0;
        $skippedCount = 0;

        foreach ($settings as $setting) {
            // ตรวจสอบว่ามี setting นี้อยู่แล้วหรือไม่
            $existing = DB::table('mlm_global_settings')
                ->where('key', $setting['key'])
                ->first();

            if ($existing) {
                // มีอยู่แล้ว - ไม่แก้ไข value แต่อัพเดท metadata ที่อาจเปลี่ยน
                // (เช่น description, allowed_values, input_type)
                DB::table('mlm_global_settings')
                    ->where('key', $setting['key'])
                    ->update([
                        'type' => $setting['type'] ?? $existing->type,
                        'input_type' => $setting['input_type'] ?? $existing->input_type,
                        'group' => $setting['group'] ?? $existing->group,
                        'description' => $setting['description'] ?? $existing->description,
                        'description_th' => $setting['description_th'] ?? $existing->description_th,
                        'placeholder' => $setting['placeholder'] ?? $existing->placeholder,
                        'unit' => $setting['unit'] ?? $existing->unit,
                        'allowed_values' => $setting['allowed_values'] ?? $existing->allowed_values,
                        'sort_order' => $setting['sort_order'] ?? $existing->sort_order,
                        // ⚠️ ไม่อัพเดท 'value' เพื่อรักษาค่าที่ผู้ใช้ตั้งไว้
                        'updated_at' => now(),
                    ]);
                $skippedCount++;
            } else {
                // ยังไม่มี - เพิ่มใหม่
                DB::table('mlm_global_settings')->insert(array_merge($setting, [
                    'is_visible' => $setting['is_visible'] ?? true,
                    'is_editable' => $setting['is_editable'] ?? true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]));
                $insertedCount++;
            }
        }

        $this->command->info("✅ MLM Global Settings: เพิ่มใหม่ {$insertedCount} รายการ, ข้าม {$skippedCount} รายการ (รักษาค่าเดิม)");
    }
}
