<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class AppThemeSetting extends Model
{
    use HasFactory;

    protected $fillable = [
        'theme_name',
        'logo_url',
        'logo_dark_url',
        'favicon_url',
        'app_icon_url',
        'splash_screen_url',
        'splash_screen_dark_url',
        'primary_color',
        'primary_dark_color',
        'primary_light_color',
        'button_primary_hover',
        'button_primary_active',
        'button_primary_disabled',
        'secondary_color',
        'secondary_dark_color',
        'secondary_light_color',
        'button_secondary_hover',
        'button_secondary_active',
        'button_secondary_disabled',
        'background_color',
        'background_dark_color',
        'background_light_color',
        'input_background',
        'input_background_dark',
        'surface_color',
        'surface_dark_color',
        'card_background',
        'card_background_dark',
        'card_border',
        'card_border_dark',
        'text_primary_color',
        'text_primary_dark_color',
        'text_secondary_color',
        'text_secondary_dark_color',
        'input_text',
        'input_text_dark',
        'input_placeholder',
        'input_placeholder_dark',
        'success_color',
        'success_dark_color',
        'badge_success',
        'warning_color',
        'warning_dark_color',
        'badge_warning',
        'error_color',
        'error_dark_color',
        'badge_error',
        'info_color',
        'info_dark_color',
        'badge_info',
        'badge_neutral',
        'link_color',
        'link_dark_color',
        'link_hover_color',
        'link_hover_dark_color',
        'border_color',
        'border_dark_color',
        'border_light_color',
        'input_border',
        'input_border_dark',
        'input_border_focus',
        'input_border_error',
        'divider_color',
        'divider_dark_color',
        'overlay_color',
        'overlay_opacity',
        'modal_background',
        'modal_background_dark',
        'font_family',
        'font_family_en',
        'font_size_base',
        'font_size_small',
        'font_size_large',
        'font_size_xlarge',
        'heading1_size',
        'heading1_weight',
        'heading1_line_height',
        'heading2_size',
        'heading2_weight',
        'heading2_line_height',
        'heading3_size',
        'heading3_weight',
        'heading3_line_height',
        'heading4_size',
        'heading4_weight',
        'heading4_line_height',
        'body_size',
        'body_weight',
        'body_line_height',
        'body_small_size',
        'body_small_weight',
        'body_small_line_height',
        'caption_size',
        'caption_weight',
        'caption_line_height',
        'button_text_size',
        'button_text_weight',
        'button_text_transform',
        'border_radius_small',
        'border_radius_medium',
        'border_radius_large',
        'border_radius_xlarge',
        'border_radius_tokens',
        'spacing_small',
        'spacing_medium',
        'spacing_large',
        'spacing_xlarge',
        'spacing_tokens',
        'shadow_tokens',
        'icon_size_small',
        'icon_size_medium',
        'icon_size_large',
        'icon_size_xlarge',
        'animation_duration',
        'animation_curve',
        'transition_fast',
        'transition_base',
        'transition_slow',
        'z_index_tokens',
        'dark_mode_enabled',
        'dark_mode_default',
        'is_active',
    ];

    protected $casts = [
        'overlay_opacity' => 'float',
        'font_size_base' => 'integer',
        'font_size_small' => 'integer',
        'font_size_large' => 'integer',
        'font_size_xlarge' => 'integer',
        'heading1_size' => 'integer',
        'heading1_line_height' => 'float',
        'heading2_size' => 'integer',
        'heading2_line_height' => 'float',
        'heading3_size' => 'integer',
        'heading3_line_height' => 'float',
        'heading4_size' => 'integer',
        'heading4_line_height' => 'float',
        'body_size' => 'integer',
        'body_line_height' => 'float',
        'body_small_size' => 'integer',
        'body_small_line_height' => 'float',
        'caption_size' => 'integer',
        'caption_line_height' => 'float',
        'button_text_size' => 'integer',
        'border_radius_small' => 'integer',
        'border_radius_medium' => 'integer',
        'border_radius_large' => 'integer',
        'border_radius_xlarge' => 'integer',
        'border_radius_tokens' => 'array',
        'spacing_small' => 'integer',
        'spacing_medium' => 'integer',
        'spacing_large' => 'integer',
        'spacing_xlarge' => 'integer',
        'spacing_tokens' => 'array',
        'shadow_tokens' => 'array',
        'icon_size_small' => 'integer',
        'icon_size_medium' => 'integer',
        'icon_size_large' => 'integer',
        'icon_size_xlarge' => 'integer',
        'animation_duration' => 'integer',
        'transition_fast' => 'integer',
        'transition_base' => 'integer',
        'transition_slow' => 'integer',
        'z_index_tokens' => 'array',
        'dark_mode_enabled' => 'boolean',
        'dark_mode_default' => 'boolean',
        'is_active' => 'boolean',
    ];

    /**
     * Get the singleton instance
     *
     * หมายเหตุ: ปิดการใช้งานตาราง app_theme_settings แล้ว เนื่องจากบังคับใช้ Arrow X Theme เท่านั้น
     * Return ค่า default object แทนการดึงจากฐานข้อมูล
     */
    public static function getInstance()
    {
        // สร้าง instance ใหม่โดยไม่บันทึกลงฐานข้อมูล
        $instance = new static([
            'theme_name' => 'Arrow X',
            'primary_color' => '#8B5CF6', // Purple
            'primary_dark_color' => '#7C3AED',
            'primary_light_color' => '#A78BFA',
            'secondary_color' => '#3B82F6', // Blue
            'secondary_dark_color' => '#2563EB',
            'secondary_light_color' => '#60A5FA',
            'background_color' => '#F9FAFB',
            'background_dark_color' => '#111827',
            'text_primary_color' => '#111827',
            'text_primary_dark_color' => '#F9FAFB',
            'success_color' => '#10B981',
            'warning_color' => '#F59E0B',
            'error_color' => '#EF4444',
            'info_color' => '#3B82F6',
            'font_family' => 'Noto Sans Thai, Inter, sans-serif',
            'font_family_en' => 'Inter, sans-serif',
            'font_size_base' => 16,
            'border_radius_medium' => 12,
            'dark_mode_enabled' => true,
            'dark_mode_default' => false,
            'is_active' => true,
        ]);

        // Set exists เป็น false เพื่อป้องกันการ save
        $instance->exists = false;

        return $instance;
    }
}
