<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

class TradingStrategy extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'user_id',
        'name',
        'slug',
        'description',
        'strategy_type',
        'indicators',
        'entry_conditions',
        'exit_conditions',
        'risk_parameters',
        'use_ai',
        'ai_model',
        'ai_config',
        'ai_confidence_threshold',
        'max_position_size',
        'stop_loss_percentage',
        'take_profit_percentage',
        'trailing_stop_percentage',
        'max_daily_loss',
        'total_pnl',
        'win_rate',
        'total_trades',
        'winning_trades',
        'losing_trades',
        'sharpe_ratio',
        'max_drawdown',
        'is_public',
        'is_for_sale',
        'price',
        'times_purchased',
        'average_rating',
        'total_reviews',
        'status',
        'is_verified',
        'last_run_at',
    ];

    protected $casts = [
        'indicators' => 'array',
        'entry_conditions' => 'array',
        'exit_conditions' => 'array',
        'risk_parameters' => 'array',
        'use_ai' => 'boolean',
        'ai_config' => 'array',
        'ai_confidence_threshold' => 'decimal:2',
        'max_position_size' => 'decimal:8',
        'stop_loss_percentage' => 'decimal:2',
        'take_profit_percentage' => 'decimal:2',
        'trailing_stop_percentage' => 'decimal:2',
        'max_daily_loss' => 'decimal:2',
        'total_pnl' => 'decimal:8',
        'win_rate' => 'decimal:2',
        'sharpe_ratio' => 'decimal:4',
        'max_drawdown' => 'decimal:2',
        'is_public' => 'boolean',
        'is_for_sale' => 'boolean',
        'price' => 'decimal:2',
        'average_rating' => 'decimal:2',
        'is_verified' => 'boolean',
        'last_run_at' => 'datetime',
    ];

    /**
     * Boot method
     */
    protected static function boot()
    {
        parent::boot();

        static::creating(function ($strategy) {
            if (empty($strategy->slug)) {
                $strategy->slug = Str::slug($strategy->name) . '-' . Str::random(8);
            }
        });
    }

    /**
     * Get the user that owns the strategy
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Get bots using this strategy
     */
    public function bots()
    {
        return $this->hasMany(TradingBot::class, 'strategy_id');
    }

    /**
     * Get signals generated by this strategy
     */
    public function signals()
    {
        return $this->hasMany(TradingSignal::class, 'strategy_id');
    }

    /**
     * Get backtests for this strategy
     */
    public function backtests()
    {
        return $this->hasMany(TradingBacktest::class, 'strategy_id');
    }

    /**
     * Get purchases of this strategy
     */
    public function purchases()
    {
        return $this->hasMany(TradingStrategyPurchase::class, 'strategy_id');
    }

    /**
     * Get reviews for this strategy
     */
    public function reviews()
    {
        return $this->hasMany(TradingStrategyReview::class, 'strategy_id');
    }

    /**
     * Calculate win rate
     */
    public function calculateWinRate(): float
    {
        if ($this->total_trades == 0) {
            return 0;
        }
        return ($this->winning_trades / $this->total_trades) * 100;
    }

    /**
     * Update performance metrics
     */
    public function updateMetrics(array $metrics): void
    {
        $this->update([
            'total_pnl' => $metrics['total_pnl'] ?? $this->total_pnl,
            'total_trades' => $metrics['total_trades'] ?? $this->total_trades,
            'winning_trades' => $metrics['winning_trades'] ?? $this->winning_trades,
            'losing_trades' => $metrics['losing_trades'] ?? $this->losing_trades,
            'win_rate' => $this->calculateWinRate(),
            'sharpe_ratio' => $metrics['sharpe_ratio'] ?? $this->sharpe_ratio,
            'max_drawdown' => $metrics['max_drawdown'] ?? $this->max_drawdown,
            'last_run_at' => now(),
        ]);
    }

    /**
     * Scope for active strategies
     */
    public function scopeActive($query)
    {
        return $query->where('status', 'active');
    }

    /**
     * Scope for public strategies
     */
    public function scopePublic($query)
    {
        return $query->where('is_public', true);
    }

    /**
     * Scope for strategies for sale
     */
    public function scopeForSale($query)
    {
        return $query->where('is_for_sale', true)->where('is_public', true);
    }

    /**
     * Scope for AI-powered strategies
     */
    public function scopeAiPowered($query)
    {
        return $query->where('use_ai', true);
    }

    /**
     * Check if strategy uses AI
     */
    public function isAiPowered(): bool
    {
        return $this->use_ai === true;
    }
}
